@file:Suppress("unused")

package com.github.cao.awa.conium.mapping.yarn.reference

import net.minecraft.core.registries.BuiltInRegistries
import net.minecraft.resources.Identifier
import net.minecraft.world.item.Item
import net.minecraft.world.item.Items

object YarnItems {
    val AIR: Item = Items.AIR
    val STONE: Item = Items.STONE
    val GRANITE: Item = Items.GRANITE
    val POLISHED_GRANITE: Item = Items.POLISHED_GRANITE
    val DIORITE: Item = Items.DIORITE
    val POLISHED_DIORITE: Item = Items.POLISHED_DIORITE
    val ANDESITE: Item = Items.ANDESITE
    val POLISHED_ANDESITE: Item = Items.POLISHED_ANDESITE
    val DEEPSLATE: Item = Items.DEEPSLATE
    val COBBLED_DEEPSLATE: Item = Items.COBBLED_DEEPSLATE
    val POLISHED_DEEPSLATE: Item = Items.POLISHED_DEEPSLATE
    val CALCITE: Item = Items.CALCITE
    val TUFF: Item = Items.TUFF
    val TUFF_SLAB: Item = Items.TUFF_SLAB
    val TUFF_STAIRS: Item = Items.TUFF_STAIRS
    val TUFF_WALL: Item = Items.TUFF_WALL
    val CHISELED_TUFF: Item = Items.CHISELED_TUFF
    val POLISHED_TUFF: Item = Items.POLISHED_TUFF
    val POLISHED_TUFF_SLAB: Item = Items.POLISHED_TUFF_SLAB
    val POLISHED_TUFF_STAIRS: Item = Items.POLISHED_TUFF_STAIRS
    val POLISHED_TUFF_WALL: Item = Items.POLISHED_TUFF_WALL
    val TUFF_BRICKS: Item = Items.TUFF_BRICKS
    val TUFF_BRICK_SLAB: Item = Items.TUFF_BRICK_SLAB
    val TUFF_BRICK_STAIRS: Item = Items.TUFF_BRICK_STAIRS
    val TUFF_BRICK_WALL: Item = Items.TUFF_BRICK_WALL
    val CHISELED_TUFF_BRICKS: Item = Items.CHISELED_TUFF_BRICKS
    val DRIPSTONE_BLOCK: Item = Items.DRIPSTONE_BLOCK
    val GRASS_BLOCK: Item = Items.GRASS_BLOCK
    val DIRT: Item = Items.DIRT
    val COARSE_DIRT: Item = Items.COARSE_DIRT
    val PODZOL: Item = Items.PODZOL
    val ROOTED_DIRT: Item = Items.ROOTED_DIRT
    val MUD: Item = Items.MUD
    val CRIMSON_NYLIUM: Item = Items.CRIMSON_NYLIUM
    val WARPED_NYLIUM: Item = Items.WARPED_NYLIUM
    val COBBLESTONE: Item = Items.COBBLESTONE
    val OAK_PLANKS: Item = Items.OAK_PLANKS
    val SPRUCE_PLANKS: Item = Items.SPRUCE_PLANKS
    val BIRCH_PLANKS: Item = Items.BIRCH_PLANKS
    val JUNGLE_PLANKS: Item = Items.JUNGLE_PLANKS
    val ACACIA_PLANKS: Item = Items.ACACIA_PLANKS
    val CHERRY_PLANKS: Item = Items.CHERRY_PLANKS
    val DARK_OAK_PLANKS: Item = Items.DARK_OAK_PLANKS
    val PALE_OAK_PLANKS: Item = Items.PALE_OAK_PLANKS
    val MANGROVE_PLANKS: Item = Items.MANGROVE_PLANKS
    val BAMBOO_PLANKS: Item = Items.BAMBOO_PLANKS
    val CRIMSON_PLANKS: Item = Items.CRIMSON_PLANKS
    val WARPED_PLANKS: Item = Items.WARPED_PLANKS
    val BAMBOO_MOSAIC: Item = Items.BAMBOO_MOSAIC
    val OAK_SAPLING: Item = Items.OAK_SAPLING
    val SPRUCE_SAPLING: Item = Items.SPRUCE_SAPLING
    val BIRCH_SAPLING: Item = Items.BIRCH_SAPLING
    val JUNGLE_SAPLING: Item = Items.JUNGLE_SAPLING
    val ACACIA_SAPLING: Item = Items.ACACIA_SAPLING
    val CHERRY_SAPLING: Item = Items.CHERRY_SAPLING
    val DARK_OAK_SAPLING: Item = Items.DARK_OAK_SAPLING
    val PALE_OAK_SAPLING: Item = Items.PALE_OAK_SAPLING
    val MANGROVE_PROPAGULE: Item = Items.MANGROVE_PROPAGULE
    val BEDROCK: Item = Items.BEDROCK
    val SAND: Item = Items.SAND
    val SUSPICIOUS_SAND: Item = Items.SUSPICIOUS_SAND
    val SUSPICIOUS_GRAVEL: Item = Items.SUSPICIOUS_GRAVEL
    val RED_SAND: Item = Items.RED_SAND
    val GRAVEL: Item = Items.GRAVEL
    val COAL_ORE: Item = Items.COAL_ORE
    val DEEPSLATE_COAL_ORE: Item = Items.DEEPSLATE_COAL_ORE
    val IRON_ORE: Item = Items.IRON_ORE
    val DEEPSLATE_IRON_ORE: Item = Items.DEEPSLATE_IRON_ORE
    val COPPER_ORE: Item = Items.COPPER_ORE
    val DEEPSLATE_COPPER_ORE: Item = Items.DEEPSLATE_COPPER_ORE
    val GOLD_ORE: Item = Items.GOLD_ORE
    val DEEPSLATE_GOLD_ORE: Item = Items.DEEPSLATE_GOLD_ORE
    val REDSTONE_ORE: Item = Items.REDSTONE_ORE
    val DEEPSLATE_REDSTONE_ORE: Item = Items.DEEPSLATE_REDSTONE_ORE
    val EMERALD_ORE: Item = Items.EMERALD_ORE
    val DEEPSLATE_EMERALD_ORE: Item = Items.DEEPSLATE_EMERALD_ORE
    val LAPIS_ORE: Item = Items.LAPIS_ORE
    val DEEPSLATE_LAPIS_ORE: Item = Items.DEEPSLATE_LAPIS_ORE
    val DIAMOND_ORE: Item = Items.DIAMOND_ORE
    val DEEPSLATE_DIAMOND_ORE: Item = Items.DEEPSLATE_DIAMOND_ORE
    val NETHER_GOLD_ORE: Item = Items.NETHER_GOLD_ORE
    val NETHER_QUARTZ_ORE: Item = Items.NETHER_QUARTZ_ORE
    val ANCIENT_DEBRIS: Item = Items.ANCIENT_DEBRIS
    val COAL_BLOCK: Item = Items.COAL_BLOCK
    val RAW_IRON_BLOCK: Item = Items.RAW_IRON_BLOCK
    val RAW_COPPER_BLOCK: Item = Items.RAW_COPPER_BLOCK
    val RAW_GOLD_BLOCK: Item = Items.RAW_GOLD_BLOCK
    val HEAVY_CORE: Item = Items.HEAVY_CORE
    val AMETHYST_BLOCK: Item = Items.AMETHYST_BLOCK
    val BUDDING_AMETHYST: Item = Items.BUDDING_AMETHYST
    val IRON_BLOCK: Item = Items.IRON_BLOCK
    val COPPER_BLOCK: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("copper_block"))
    val GOLD_BLOCK: Item = Items.GOLD_BLOCK
    val DIAMOND_BLOCK: Item = Items.DIAMOND_BLOCK
    val NETHERITE_BLOCK: Item = Items.NETHERITE_BLOCK
    val EXPOSED_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("exposed_copper"))
    val WEATHERED_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("weathered_copper"))
    val OXIDIZED_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("oxidized_copper"))
    val CHISELED_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("chiseled_copper"))
    val EXPOSED_CHISELED_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("exposed_chiseled_copper"))
    val WEATHERED_CHISELED_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("weathered_chiseled_copper"))
    val OXIDIZED_CHISELED_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("oxidized_chiseled_copper"))
    val CUT_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("cut_copper"))
    val EXPOSED_CUT_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("exposed_cut_copper"))
    val WEATHERED_CUT_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("weathered_cut_copper"))
    val OXIDIZED_CUT_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("oxidized_cut_copper"))
    val CUT_COPPER_STAIRS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("cut_copper_stairs"))
    val EXPOSED_CUT_COPPER_STAIRS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("exposed_cut_copper_stairs"))
    val WEATHERED_CUT_COPPER_STAIRS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("weathered_cut_copper_stairs"))
    val OXIDIZED_CUT_COPPER_STAIRS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("oxidized_cut_copper_stairs"))
    val CUT_COPPER_SLAB: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("cut_copper_slab"))
    val EXPOSED_CUT_COPPER_SLAB: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("exposed_cut_copper_slab"))
    val WEATHERED_CUT_COPPER_SLAB: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("weathered_cut_copper_slab"))
    val OXIDIZED_CUT_COPPER_SLAB: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("oxidized_cut_copper_slab"))
    val WAXED_COPPER_BLOCK: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_copper_block"))
    val WAXED_EXPOSED_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_exposed_copper"))
    val WAXED_WEATHERED_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_weathered_copper"))
    val WAXED_OXIDIZED_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_oxidized_copper"))
    val WAXED_CHISELED_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_chiseled_copper"))
    val WAXED_EXPOSED_CHISELED_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_exposed_chiseled_copper"))
    val WAXED_WEATHERED_CHISELED_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_weathered_chiseled_copper"))
    val WAXED_OXIDIZED_CHISELED_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_oxidized_chiseled_copper"))
    val WAXED_CUT_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_cut_copper"))
    val WAXED_EXPOSED_CUT_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_exposed_cut_copper"))
    val WAXED_WEATHERED_CUT_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_weathered_cut_copper"))
    val WAXED_OXIDIZED_CUT_COPPER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_oxidized_cut_copper"))
    val WAXED_CUT_COPPER_STAIRS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_cut_copper_stairs"))
    val WAXED_EXPOSED_CUT_COPPER_SLAB: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_exposed_cut_copper_slab"))
    val WAXED_WEATHERED_CUT_COPPER_SLAB: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_weathered_cut_copper_slab"))
    val WAXED_OXIDIZED_CUT_COPPER_SLAB: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_oxidized_cut_copper_slab"))
    val WAXED_CUT_COPPER_SLAB: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_cut_copper_slab"))
    val WAXED_EXPOSED_CUT_COPPER_STAIRS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_exposed_cut_copper_stairs"))
    val WAXED_WEATHERED_CUT_COPPER_STAIRS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_weathered_cut_copper_stairs"))
    val WAXED_OXIDIZED_CUT_COPPER_STAIRS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_oxidized_cut_copper_stairs"))
    val OAK_LOG: Item = Items.OAK_LOG
    val SPRUCE_LOG: Item = Items.SPRUCE_LOG
    val BIRCH_LOG: Item = Items.BIRCH_LOG
    val JUNGLE_LOG: Item = Items.JUNGLE_LOG
    val ACACIA_LOG: Item = Items.ACACIA_LOG
    val CHERRY_LOG: Item = Items.CHERRY_LOG
    val PALE_OAK_LOG: Item = Items.PALE_OAK_LOG
    val DARK_OAK_LOG: Item = Items.DARK_OAK_LOG
    val MANGROVE_LOG: Item = Items.MANGROVE_LOG
    val MANGROVE_ROOTS: Item = Items.MANGROVE_ROOTS
    val MUDDY_MANGROVE_ROOTS: Item = Items.MUDDY_MANGROVE_ROOTS
    val CRIMSON_STEM: Item = Items.CRIMSON_STEM
    val WARPED_STEM: Item = Items.WARPED_STEM
    val BAMBOO_BLOCK: Item = Items.BAMBOO_BLOCK
    val STRIPPED_OAK_LOG: Item = Items.STRIPPED_OAK_LOG
    val STRIPPED_SPRUCE_LOG: Item = Items.STRIPPED_SPRUCE_LOG
    val STRIPPED_BIRCH_LOG: Item = Items.STRIPPED_BIRCH_LOG
    val STRIPPED_JUNGLE_LOG: Item = Items.STRIPPED_JUNGLE_LOG
    val STRIPPED_ACACIA_LOG: Item = Items.STRIPPED_ACACIA_LOG
    val STRIPPED_CHERRY_LOG: Item = Items.STRIPPED_CHERRY_LOG
    val STRIPPED_DARK_OAK_LOG: Item = Items.STRIPPED_DARK_OAK_LOG
    val STRIPPED_PALE_OAK_LOG: Item = Items.STRIPPED_PALE_OAK_LOG
    val STRIPPED_MANGROVE_LOG: Item = Items.STRIPPED_MANGROVE_LOG
    val STRIPPED_CRIMSON_STEM: Item = Items.STRIPPED_CRIMSON_STEM
    val STRIPPED_WARPED_STEM: Item = Items.STRIPPED_WARPED_STEM
    val STRIPPED_OAK_WOOD: Item = Items.STRIPPED_OAK_WOOD
    val STRIPPED_SPRUCE_WOOD: Item = Items.STRIPPED_SPRUCE_WOOD
    val STRIPPED_BIRCH_WOOD: Item = Items.STRIPPED_BIRCH_WOOD
    val STRIPPED_JUNGLE_WOOD: Item = Items.STRIPPED_JUNGLE_WOOD
    val STRIPPED_ACACIA_WOOD: Item = Items.STRIPPED_ACACIA_WOOD
    val STRIPPED_CHERRY_WOOD: Item = Items.STRIPPED_CHERRY_WOOD
    val STRIPPED_DARK_OAK_WOOD: Item = Items.STRIPPED_DARK_OAK_WOOD
    val STRIPPED_PALE_OAK_WOOD: Item = Items.STRIPPED_PALE_OAK_WOOD
    val STRIPPED_MANGROVE_WOOD: Item = Items.STRIPPED_MANGROVE_WOOD
    val STRIPPED_CRIMSON_HYPHAE: Item = Items.STRIPPED_CRIMSON_HYPHAE
    val STRIPPED_WARPED_HYPHAE: Item = Items.STRIPPED_WARPED_HYPHAE
    val STRIPPED_BAMBOO_BLOCK: Item = Items.STRIPPED_BAMBOO_BLOCK
    val OAK_WOOD: Item = Items.OAK_WOOD
    val SPRUCE_WOOD: Item = Items.SPRUCE_WOOD
    val BIRCH_WOOD: Item = Items.BIRCH_WOOD
    val JUNGLE_WOOD: Item = Items.JUNGLE_WOOD
    val ACACIA_WOOD: Item = Items.ACACIA_WOOD
    val CHERRY_WOOD: Item = Items.CHERRY_WOOD
    val PALE_OAK_WOOD: Item = Items.PALE_OAK_WOOD
    val DARK_OAK_WOOD: Item = Items.DARK_OAK_WOOD
    val MANGROVE_WOOD: Item = Items.MANGROVE_WOOD
    val CRIMSON_HYPHAE: Item = Items.CRIMSON_HYPHAE
    val WARPED_HYPHAE: Item = Items.WARPED_HYPHAE
    val OAK_LEAVES: Item = Items.OAK_LEAVES
    val SPRUCE_LEAVES: Item = Items.SPRUCE_LEAVES
    val BIRCH_LEAVES: Item = Items.BIRCH_LEAVES
    val JUNGLE_LEAVES: Item = Items.JUNGLE_LEAVES
    val ACACIA_LEAVES: Item = Items.ACACIA_LEAVES
    val CHERRY_LEAVES: Item = Items.CHERRY_LEAVES
    val DARK_OAK_LEAVES: Item = Items.DARK_OAK_LEAVES
    val PALE_OAK_LEAVES: Item = Items.PALE_OAK_LEAVES
    val MANGROVE_LEAVES: Item = Items.MANGROVE_LEAVES
    val AZALEA_LEAVES: Item = Items.AZALEA_LEAVES
    val FLOWERING_AZALEA_LEAVES: Item = Items.FLOWERING_AZALEA_LEAVES
    val SPONGE: Item = Items.SPONGE
    val WET_SPONGE: Item = Items.WET_SPONGE
    val GLASS: Item = Items.GLASS
    val TINTED_GLASS: Item = Items.TINTED_GLASS
    val LAPIS_BLOCK: Item = Items.LAPIS_BLOCK
    val SANDSTONE: Item = Items.SANDSTONE
    val CHISELED_SANDSTONE: Item = Items.CHISELED_SANDSTONE
    val CUT_SANDSTONE: Item = Items.CUT_SANDSTONE
    val COBWEB: Item = Items.COBWEB
    val SHORT_GRASS: Item = Items.SHORT_GRASS
    val FERN: Item = Items.FERN
    val AZALEA: Item = Items.AZALEA
    val FLOWERING_AZALEA: Item = Items.FLOWERING_AZALEA
    val DEAD_BUSH: Item = Items.DEAD_BUSH
    val SEAGRASS: Item = Items.SEAGRASS
    val SEA_PICKLE: Item = Items.SEA_PICKLE
    val WHITE_WOOL: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("white_wool"))
    val ORANGE_WOOL: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("orange_wool"))
    val MAGENTA_WOOL: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("magenta_wool"))
    val LIGHT_BLUE_WOOL: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_blue_wool"))
    val YELLOW_WOOL: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("yellow_wool"))
    val LIME_WOOL: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("lime_wool"))
    val PINK_WOOL: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("pink_wool"))
    val GRAY_WOOL: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("gray_wool"))
    val LIGHT_GRAY_WOOL: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_gray_wool"))
    val CYAN_WOOL: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("cyan_wool"))
    val PURPLE_WOOL: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("purple_wool"))
    val BLUE_WOOL: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("blue_wool"))
    val BROWN_WOOL: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("brown_wool"))
    val GREEN_WOOL: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("green_wool"))
    val RED_WOOL: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("red_wool"))
    val BLACK_WOOL: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("black_wool"))
    val DANDELION: Item = Items.DANDELION
    val OPEN_EYEBLOSSOM: Item = Items.OPEN_EYEBLOSSOM
    val CLOSED_EYEBLOSSOM: Item = Items.CLOSED_EYEBLOSSOM
    val POPPY: Item = Items.POPPY
    val BLUE_ORCHID: Item = Items.BLUE_ORCHID
    val ALLIUM: Item = Items.ALLIUM
    val AZURE_BLUET: Item = Items.AZURE_BLUET
    val RED_TULIP: Item = Items.RED_TULIP
    val ORANGE_TULIP: Item = Items.ORANGE_TULIP
    val WHITE_TULIP: Item = Items.WHITE_TULIP
    val PINK_TULIP: Item = Items.PINK_TULIP
    val OXEYE_DAISY: Item = Items.OXEYE_DAISY
    val CORNFLOWER: Item = Items.CORNFLOWER
    val LILY_OF_THE_VALLEY: Item = Items.LILY_OF_THE_VALLEY
    val WITHER_ROSE: Item = Items.WITHER_ROSE
    val TORCHFLOWER: Item = Items.TORCHFLOWER
    val PITCHER_PLANT: Item = Items.PITCHER_PLANT
    val SPORE_BLOSSOM: Item = Items.SPORE_BLOSSOM
    val BROWN_MUSHROOM: Item = Items.BROWN_MUSHROOM
    val RED_MUSHROOM: Item = Items.RED_MUSHROOM
    val CRIMSON_FUNGUS: Item = Items.CRIMSON_FUNGUS
    val WARPED_FUNGUS: Item = Items.WARPED_FUNGUS
    val CRIMSON_ROOTS: Item = Items.CRIMSON_ROOTS
    val WARPED_ROOTS: Item = Items.WARPED_ROOTS
    val NETHER_SPROUTS: Item = Items.NETHER_SPROUTS
    val WEEPING_VINES: Item = Items.WEEPING_VINES
    val TWISTING_VINES: Item = Items.TWISTING_VINES
    val SUGAR_CANE: Item = Items.SUGAR_CANE
    val KELP: Item = Items.KELP
    val PINK_PETALS: Item = Items.PINK_PETALS
    val MOSS_CARPET: Item = Items.MOSS_CARPET
    val MOSS_BLOCK: Item = Items.MOSS_BLOCK
    val PALE_MOSS_CARPET: Item = Items.PALE_MOSS_CARPET
    val PALE_HANGING_MOSS: Item = Items.PALE_HANGING_MOSS
    val PALE_MOSS_BLOCK: Item = Items.PALE_MOSS_BLOCK
    val HANGING_ROOTS: Item = Items.HANGING_ROOTS
    val BIG_DRIPLEAF: Item = Items.BIG_DRIPLEAF
    val SMALL_DRIPLEAF: Item = Items.SMALL_DRIPLEAF
    val BAMBOO: Item = Items.BAMBOO
    val OAK_SLAB: Item = Items.OAK_SLAB
    val SPRUCE_SLAB: Item = Items.SPRUCE_SLAB
    val BIRCH_SLAB: Item = Items.BIRCH_SLAB
    val JUNGLE_SLAB: Item = Items.JUNGLE_SLAB
    val ACACIA_SLAB: Item = Items.ACACIA_SLAB
    val CHERRY_SLAB: Item = Items.CHERRY_SLAB
    val DARK_OAK_SLAB: Item = Items.DARK_OAK_SLAB
    val PALE_OAK_SLAB: Item = Items.PALE_OAK_SLAB
    val MANGROVE_SLAB: Item = Items.MANGROVE_SLAB
    val BAMBOO_SLAB: Item = Items.BAMBOO_SLAB
    val BAMBOO_MOSAIC_SLAB: Item = Items.BAMBOO_MOSAIC_SLAB
    val CRIMSON_SLAB: Item = Items.CRIMSON_SLAB
    val WARPED_SLAB: Item = Items.WARPED_SLAB
    val STONE_SLAB: Item = Items.STONE_SLAB
    val SMOOTH_STONE_SLAB: Item = Items.SMOOTH_STONE_SLAB
    val SANDSTONE_SLAB: Item = Items.SANDSTONE_SLAB
    val CUT_SANDSTONE_SLAB: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("cut_sandstone_slab"))
    val PETRIFIED_OAK_SLAB: Item = Items.PETRIFIED_OAK_SLAB
    val COBBLESTONE_SLAB: Item = Items.COBBLESTONE_SLAB
    val BRICK_SLAB: Item = Items.BRICK_SLAB
    val STONE_BRICK_SLAB: Item = Items.STONE_BRICK_SLAB
    val MUD_BRICK_SLAB: Item = Items.MUD_BRICK_SLAB
    val NETHER_BRICK_SLAB: Item = Items.NETHER_BRICK_SLAB
    val QUARTZ_SLAB: Item = Items.QUARTZ_SLAB
    val RED_SANDSTONE_SLAB: Item = Items.RED_SANDSTONE_SLAB
    val CUT_RED_SANDSTONE_SLAB: Item = Items.CUT_RED_SANDSTONE_SLAB
    val PURPUR_SLAB: Item = Items.PURPUR_SLAB
    val PRISMARINE_SLAB: Item = Items.PRISMARINE_SLAB
    val PRISMARINE_BRICK_SLAB: Item = Items.PRISMARINE_BRICK_SLAB
    val DARK_PRISMARINE_SLAB: Item = Items.DARK_PRISMARINE_SLAB
    val SMOOTH_QUARTZ: Item = Items.SMOOTH_QUARTZ
    val SMOOTH_RED_SANDSTONE: Item = Items.SMOOTH_RED_SANDSTONE
    val SMOOTH_SANDSTONE: Item = Items.SMOOTH_SANDSTONE
    val SMOOTH_STONE: Item = Items.SMOOTH_STONE
    val BRICKS: Item = Items.BRICKS
    val BOOKSHELF: Item = Items.BOOKSHELF
    val CHISELED_BOOKSHELF: Item = Items.CHISELED_BOOKSHELF
    val DECORATED_POT: Item = Items.DECORATED_POT
    val MOSSY_COBBLESTONE: Item = Items.MOSSY_COBBLESTONE
    val OBSIDIAN: Item = Items.OBSIDIAN
    val TORCH: Item = Items.TORCH
    val END_ROD: Item = Items.END_ROD
    val CHORUS_PLANT: Item = Items.CHORUS_PLANT
    val CHORUS_FLOWER: Item = Items.CHORUS_FLOWER
    val PURPUR_BLOCK: Item = Items.PURPUR_BLOCK
    val PURPUR_PILLAR: Item = Items.PURPUR_PILLAR
    val PURPUR_STAIRS: Item = Items.PURPUR_STAIRS
    val SPAWNER: Item = Items.SPAWNER
    val CREAKING_HEART: Item = Items.CREAKING_HEART
    val CHEST: Item = Items.CHEST
    val CRAFTING_TABLE: Item = Items.CRAFTING_TABLE
    val FARMLAND: Item = Items.FARMLAND
    val FURNACE: Item = Items.FURNACE
    val LADDER: Item = Items.LADDER
    val COBBLESTONE_STAIRS: Item = Items.COBBLESTONE_STAIRS
    val SNOW: Item = Items.SNOW
    val ICE: Item = Items.ICE
    val SNOW_BLOCK: Item = Items.SNOW_BLOCK
    val CACTUS: Item = Items.CACTUS
    val CLAY: Item = Items.CLAY
    val JUKEBOX: Item = Items.JUKEBOX
    val OAK_FENCE: Item = Items.OAK_FENCE
    val SPRUCE_FENCE: Item = Items.SPRUCE_FENCE
    val BIRCH_FENCE: Item = Items.BIRCH_FENCE
    val JUNGLE_FENCE: Item = Items.JUNGLE_FENCE
    val ACACIA_FENCE: Item = Items.ACACIA_FENCE
    val CHERRY_FENCE: Item = Items.CHERRY_FENCE
    val DARK_OAK_FENCE: Item = Items.DARK_OAK_FENCE
    val PALE_OAK_FENCE: Item = Items.PALE_OAK_FENCE
    val MANGROVE_FENCE: Item = Items.MANGROVE_FENCE
    val BAMBOO_FENCE: Item = Items.BAMBOO_FENCE
    val CRIMSON_FENCE: Item = Items.CRIMSON_FENCE
    val WARPED_FENCE: Item = Items.WARPED_FENCE
    val PUMPKIN: Item = Items.PUMPKIN
    val CARVED_PUMPKIN: Item = Items.CARVED_PUMPKIN
    val JACK_O_LANTERN: Item = Items.JACK_O_LANTERN
    val NETHERRACK: Item = Items.NETHERRACK
    val SOUL_SAND: Item = Items.SOUL_SAND
    val SOUL_SOIL: Item = Items.SOUL_SOIL
    val BASALT: Item = Items.BASALT
    val POLISHED_BASALT: Item = Items.POLISHED_BASALT
    val SMOOTH_BASALT: Item = Items.SMOOTH_BASALT
    val SOUL_TORCH: Item = Items.SOUL_TORCH
    val GLOWSTONE: Item = Items.GLOWSTONE
    val INFESTED_STONE: Item = Items.INFESTED_STONE
    val INFESTED_COBBLESTONE: Item = Items.INFESTED_COBBLESTONE
    val INFESTED_STONE_BRICKS: Item = Items.INFESTED_STONE_BRICKS
    val INFESTED_MOSSY_STONE_BRICKS: Item = Items.INFESTED_MOSSY_STONE_BRICKS
    val INFESTED_CRACKED_STONE_BRICKS: Item = Items.INFESTED_CRACKED_STONE_BRICKS
    val INFESTED_CHISELED_STONE_BRICKS: Item = Items.INFESTED_CHISELED_STONE_BRICKS
    val INFESTED_DEEPSLATE: Item = Items.INFESTED_DEEPSLATE
    val STONE_BRICKS: Item = Items.STONE_BRICKS
    val MOSSY_STONE_BRICKS: Item = Items.MOSSY_STONE_BRICKS
    val CRACKED_STONE_BRICKS: Item = Items.CRACKED_STONE_BRICKS
    val CHISELED_STONE_BRICKS: Item = Items.CHISELED_STONE_BRICKS
    val PACKED_MUD: Item = Items.PACKED_MUD
    val MUD_BRICKS: Item = Items.MUD_BRICKS
    val DEEPSLATE_BRICKS: Item = Items.DEEPSLATE_BRICKS
    val CRACKED_DEEPSLATE_BRICKS: Item = Items.CRACKED_DEEPSLATE_BRICKS
    val DEEPSLATE_TILES: Item = Items.DEEPSLATE_TILES
    val CRACKED_DEEPSLATE_TILES: Item = Items.CRACKED_DEEPSLATE_TILES
    val CHISELED_DEEPSLATE: Item = Items.CHISELED_DEEPSLATE
    val REINFORCED_DEEPSLATE: Item = Items.REINFORCED_DEEPSLATE
    val BROWN_MUSHROOM_BLOCK: Item = Items.BROWN_MUSHROOM_BLOCK
    val RED_MUSHROOM_BLOCK: Item = Items.RED_MUSHROOM_BLOCK
    val MUSHROOM_STEM: Item = Items.MUSHROOM_STEM
    val IRON_BARS: Item = Items.IRON_BARS
    val IRON_CHAIN: Item = Items.IRON_CHAIN
    val GLASS_PANE: Item = Items.GLASS_PANE
    val MELON: Item = Items.MELON
    val VINE: Item = Items.VINE
    val GLOW_LICHEN: Item = Items.GLOW_LICHEN
    val RESIN_CLUMP: Item = Items.RESIN_CLUMP
    val RESIN_BLOCK: Item = Items.RESIN_BLOCK
    val RESIN_BRICKS: Item = Items.RESIN_BRICKS
    val RESIN_BRICK_STAIRS: Item = Items.RESIN_BRICK_STAIRS
    val RESIN_BRICK_SLAB: Item = Items.RESIN_BRICK_SLAB
    val RESIN_BRICK_WALL: Item = Items.RESIN_BRICK_WALL
    val CHISELED_RESIN_BRICKS: Item = Items.CHISELED_RESIN_BRICKS
    val BRICK_STAIRS: Item = Items.BRICK_STAIRS
    val STONE_BRICK_STAIRS: Item = Items.STONE_BRICK_STAIRS
    val MUD_BRICK_STAIRS: Item = Items.MUD_BRICK_STAIRS
    val MYCELIUM: Item = Items.MYCELIUM
    val LILY_PAD: Item = Items.LILY_PAD
    val NETHER_BRICKS: Item = Items.NETHER_BRICKS
    val CRACKED_NETHER_BRICKS: Item = Items.CRACKED_NETHER_BRICKS
    val CHISELED_NETHER_BRICKS: Item = Items.CHISELED_NETHER_BRICKS
    val NETHER_BRICK_FENCE: Item = Items.NETHER_BRICK_FENCE
    val NETHER_BRICK_STAIRS: Item = Items.NETHER_BRICK_STAIRS
    val SCULK: Item = Items.SCULK
    val SCULK_VEIN: Item = Items.SCULK_VEIN
    val SCULK_CATALYST: Item = Items.SCULK_CATALYST
    val SCULK_SHRIEKER: Item = Items.SCULK_SHRIEKER
    val ENCHANTING_TABLE: Item = Items.ENCHANTING_TABLE
    val END_PORTAL_FRAME: Item = Items.END_PORTAL_FRAME
    val END_STONE: Item = Items.END_STONE
    val END_STONE_BRICKS: Item = Items.END_STONE_BRICKS
    val DRAGON_EGG: Item = Items.DRAGON_EGG
    val SANDSTONE_STAIRS: Item = Items.SANDSTONE_STAIRS
    val ENDER_CHEST: Item = Items.ENDER_CHEST
    val EMERALD_BLOCK: Item = Items.EMERALD_BLOCK
    val OAK_STAIRS: Item = Items.OAK_STAIRS
    val SPRUCE_STAIRS: Item = Items.SPRUCE_STAIRS
    val BIRCH_STAIRS: Item = Items.BIRCH_STAIRS
    val JUNGLE_STAIRS: Item = Items.JUNGLE_STAIRS
    val ACACIA_STAIRS: Item = Items.ACACIA_STAIRS
    val CHERRY_STAIRS: Item = Items.CHERRY_STAIRS
    val DARK_OAK_STAIRS: Item = Items.DARK_OAK_STAIRS
    val PALE_OAK_STAIRS: Item = Items.PALE_OAK_STAIRS
    val MANGROVE_STAIRS: Item = Items.MANGROVE_STAIRS
    val BAMBOO_STAIRS: Item = Items.BAMBOO_STAIRS
    val BAMBOO_MOSAIC_STAIRS: Item = Items.BAMBOO_MOSAIC_STAIRS
    val CRIMSON_STAIRS: Item = Items.CRIMSON_STAIRS
    val WARPED_STAIRS: Item = Items.WARPED_STAIRS
    val COMMAND_BLOCK: Item = Items.COMMAND_BLOCK
    val BEACON: Item = Items.BEACON
    val COBBLESTONE_WALL: Item = Items.COBBLESTONE_WALL
    val MOSSY_COBBLESTONE_WALL: Item = Items.MOSSY_COBBLESTONE_WALL
    val BRICK_WALL: Item = Items.BRICK_WALL
    val PRISMARINE_WALL: Item = Items.PRISMARINE_WALL
    val RED_SANDSTONE_WALL: Item = Items.RED_SANDSTONE_WALL
    val MOSSY_STONE_BRICK_WALL: Item = Items.MOSSY_STONE_BRICK_WALL
    val GRANITE_WALL: Item = Items.GRANITE_WALL
    val STONE_BRICK_WALL: Item = Items.STONE_BRICK_WALL
    val MUD_BRICK_WALL: Item = Items.MUD_BRICK_WALL
    val NETHER_BRICK_WALL: Item = Items.NETHER_BRICK_WALL
    val ANDESITE_WALL: Item = Items.ANDESITE_WALL
    val RED_NETHER_BRICK_WALL: Item = Items.RED_NETHER_BRICK_WALL
    val SANDSTONE_WALL: Item = Items.SANDSTONE_WALL
    val END_STONE_BRICK_WALL: Item = Items.END_STONE_BRICK_WALL
    val DIORITE_WALL: Item = Items.DIORITE_WALL
    val BLACKSTONE_WALL: Item = Items.BLACKSTONE_WALL
    val POLISHED_BLACKSTONE_WALL: Item = Items.POLISHED_BLACKSTONE_WALL
    val POLISHED_BLACKSTONE_BRICK_SLAB: Item = Items.POLISHED_BLACKSTONE_BRICK_SLAB
    val COBBLED_DEEPSLATE_WALL: Item = Items.COBBLED_DEEPSLATE_WALL
    val POLISHED_DEEPSLATE_WALL: Item = Items.POLISHED_DEEPSLATE_WALL
    val DEEPSLATE_BRICK_WALL: Item = Items.DEEPSLATE_BRICK_WALL
    val DEEPSLATE_TILE_WALL: Item = Items.DEEPSLATE_TILE_WALL
    val ANVIL: Item = Items.ANVIL
    val CHIPPED_ANVIL: Item = Items.CHIPPED_ANVIL
    val DAMAGED_ANVIL: Item = Items.DAMAGED_ANVIL
    val CHISELED_QUARTZ_BLOCK: Item = Items.CHISELED_QUARTZ_BLOCK
    val QUARTZ_BLOCK: Item = Items.QUARTZ_BLOCK
    val QUARTZ_BRICKS: Item = Items.QUARTZ_BRICKS
    val QUARTZ_PILLAR: Item = Items.QUARTZ_PILLAR
    val QUARTZ_STAIRS: Item = Items.QUARTZ_STAIRS
    val WHITE_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("white_terracotta"))
    val ORANGE_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("orange_terracotta"))
    val MAGENTA_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("magenta_terracotta"))
    val LIGHT_BLUE_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_blue_terracotta"))
    val YELLOW_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("yellow_terracotta"))
    val LIME_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("lime_terracotta"))
    val PINK_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("pink_terracotta"))
    val GRAY_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("gray_terracotta"))
    val LIGHT_GRAY_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_gray_terracotta"))
    val CYAN_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("cyan_terracotta"))
    val PURPLE_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("purple_terracotta"))
    val BLUE_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("blue_terracotta"))
    val BROWN_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("brown_terracotta"))
    val GREEN_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("green_terracotta"))
    val RED_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("red_terracotta"))
    val BLACK_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("black_terracotta"))
    val BARRIER: Item = Items.BARRIER
    val LIGHT: Item = Items.LIGHT
    val HAY_BLOCK: Item = Items.HAY_BLOCK
    val WHITE_CARPET: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("white_carpet"))
    val ORANGE_CARPET: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("orange_carpet"))
    val MAGENTA_CARPET: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("magenta_carpet"))
    val LIGHT_BLUE_CARPET: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_blue_carpet"))
    val YELLOW_CARPET: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("yellow_carpet"))
    val LIME_CARPET: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("lime_carpet"))
    val PINK_CARPET: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("pink_carpet"))
    val GRAY_CARPET: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("gray_carpet"))
    val LIGHT_GRAY_CARPET: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_gray_carpet"))
    val CYAN_CARPET: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("cyan_carpet"))
    val PURPLE_CARPET: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("purple_carpet"))
    val BLUE_CARPET: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("blue_carpet"))
    val BROWN_CARPET: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("brown_carpet"))
    val GREEN_CARPET: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("green_carpet"))
    val RED_CARPET: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("red_carpet"))
    val BLACK_CARPET: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("black_carpet"))
    val TERRACOTTA: Item = Items.TERRACOTTA
    val PACKED_ICE: Item = Items.PACKED_ICE
    val DIRT_PATH: Item = Items.DIRT_PATH
    val SUNFLOWER: Item = Items.SUNFLOWER
    val LILAC: Item = Items.LILAC
    val ROSE_BUSH: Item = Items.ROSE_BUSH
    val PEONY: Item = Items.PEONY
    val TALL_GRASS: Item = Items.TALL_GRASS
    val LARGE_FERN: Item = Items.LARGE_FERN
    val WHITE_STAINED_GLASS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("white_stained_glass"))
    val ORANGE_STAINED_GLASS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("orange_stained_glass"))
    val MAGENTA_STAINED_GLASS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("magenta_stained_glass"))
    val LIGHT_BLUE_STAINED_GLASS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_blue_stained_glass"))
    val YELLOW_STAINED_GLASS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("yellow_stained_glass"))
    val LIME_STAINED_GLASS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("lime_stained_glass"))
    val PINK_STAINED_GLASS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("pink_stained_glass"))
    val GRAY_STAINED_GLASS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("gray_stained_glass"))
    val LIGHT_GRAY_STAINED_GLASS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_gray_stained_glass"))
    val CYAN_STAINED_GLASS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("cyan_stained_glass"))
    val PURPLE_STAINED_GLASS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("purple_stained_glass"))
    val BLUE_STAINED_GLASS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("blue_stained_glass"))
    val BROWN_STAINED_GLASS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("brown_stained_glass"))
    val GREEN_STAINED_GLASS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("green_stained_glass"))
    val RED_STAINED_GLASS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("red_stained_glass"))
    val BLACK_STAINED_GLASS: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("black_stained_glass"))
    val WHITE_STAINED_GLASS_PANE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("white_stained_glass_pane"))
    val ORANGE_STAINED_GLASS_PANE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("orange_stained_glass_pane"))
    val MAGENTA_STAINED_GLASS_PANE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("magenta_stained_glass_pane"))
    val LIGHT_BLUE_STAINED_GLASS_PANE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_blue_stained_glass_pane"))
    val YELLOW_STAINED_GLASS_PANE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("yellow_stained_glass_pane"))
    val LIME_STAINED_GLASS_PANE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("lime_stained_glass_pane"))
    val PINK_STAINED_GLASS_PANE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("pink_stained_glass_pane"))
    val GRAY_STAINED_GLASS_PANE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("gray_stained_glass_pane"))
    val LIGHT_GRAY_STAINED_GLASS_PANE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_gray_stained_glass_pane"))
    val CYAN_STAINED_GLASS_PANE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("cyan_stained_glass_pane"))
    val PURPLE_STAINED_GLASS_PANE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("purple_stained_glass_pane"))
    val BLUE_STAINED_GLASS_PANE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("blue_stained_glass_pane"))
    val BROWN_STAINED_GLASS_PANE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("brown_stained_glass_pane"))
    val GREEN_STAINED_GLASS_PANE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("green_stained_glass_pane"))
    val RED_STAINED_GLASS_PANE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("red_stained_glass_pane"))
    val BLACK_STAINED_GLASS_PANE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("black_stained_glass_pane"))
    val PRISMARINE: Item = Items.PRISMARINE
    val PRISMARINE_BRICKS: Item = Items.PRISMARINE_BRICKS
    val DARK_PRISMARINE: Item = Items.DARK_PRISMARINE
    val PRISMARINE_STAIRS: Item = Items.PRISMARINE_STAIRS
    val PRISMARINE_BRICK_STAIRS: Item = Items.PRISMARINE_BRICK_STAIRS
    val DARK_PRISMARINE_STAIRS: Item = Items.DARK_PRISMARINE_STAIRS
    val SEA_LANTERN: Item = Items.SEA_LANTERN
    val RED_SANDSTONE: Item = Items.RED_SANDSTONE
    val CHISELED_RED_SANDSTONE: Item = Items.CHISELED_RED_SANDSTONE
    val CUT_RED_SANDSTONE: Item = Items.CUT_RED_SANDSTONE
    val RED_SANDSTONE_STAIRS: Item = Items.RED_SANDSTONE_STAIRS
    val REPEATING_COMMAND_BLOCK: Item = Items.REPEATING_COMMAND_BLOCK
    val CHAIN_COMMAND_BLOCK: Item = Items.CHAIN_COMMAND_BLOCK
    val MAGMA_BLOCK: Item = Items.MAGMA_BLOCK
    val NETHER_WART_BLOCK: Item = Items.NETHER_WART_BLOCK
    val WARPED_WART_BLOCK: Item = Items.WARPED_WART_BLOCK
    val RED_NETHER_BRICKS: Item = Items.RED_NETHER_BRICKS
    val BONE_BLOCK: Item = Items.BONE_BLOCK
    val STRUCTURE_VOID: Item = Items.STRUCTURE_VOID
    val SHULKER_BOX: Item = Items.SHULKER_BOX
    val WHITE_SHULKER_BOX: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("white_shulker_box"))
    val ORANGE_SHULKER_BOX: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("orange_shulker_box"))
    val MAGENTA_SHULKER_BOX: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("magenta_shulker_box"))
    val LIGHT_BLUE_SHULKER_BOX: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_blue_shulker_box"))
    val YELLOW_SHULKER_BOX: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("yellow_shulker_box"))
    val LIME_SHULKER_BOX: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("lime_shulker_box"))
    val PINK_SHULKER_BOX: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("pink_shulker_box"))
    val GRAY_SHULKER_BOX: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("gray_shulker_box"))
    val LIGHT_GRAY_SHULKER_BOX: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_gray_shulker_box"))
    val CYAN_SHULKER_BOX: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("cyan_shulker_box"))
    val PURPLE_SHULKER_BOX: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("purple_shulker_box"))
    val BLUE_SHULKER_BOX: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("blue_shulker_box"))
    val BROWN_SHULKER_BOX: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("brown_shulker_box"))
    val GREEN_SHULKER_BOX: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("green_shulker_box"))
    val RED_SHULKER_BOX: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("red_shulker_box"))
    val BLACK_SHULKER_BOX: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("black_shulker_box"))
    val WHITE_GLAZED_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("white_glazed_terracotta"))
    val ORANGE_GLAZED_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("orange_glazed_terracotta"))
    val MAGENTA_GLAZED_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("magenta_glazed_terracotta"))
    val LIGHT_BLUE_GLAZED_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_blue_glazed_terracotta"))
    val YELLOW_GLAZED_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("yellow_glazed_terracotta"))
    val LIME_GLAZED_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("lime_glazed_terracotta"))
    val PINK_GLAZED_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("pink_glazed_terracotta"))
    val GRAY_GLAZED_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("gray_glazed_terracotta"))
    val LIGHT_GRAY_GLAZED_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_gray_glazed_terracotta"))
    val CYAN_GLAZED_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("cyan_glazed_terracotta"))
    val PURPLE_GLAZED_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("purple_glazed_terracotta"))
    val BLUE_GLAZED_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("blue_glazed_terracotta"))
    val BROWN_GLAZED_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("brown_glazed_terracotta"))
    val GREEN_GLAZED_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("green_glazed_terracotta"))
    val RED_GLAZED_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("red_glazed_terracotta"))
    val BLACK_GLAZED_TERRACOTTA: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("black_glazed_terracotta"))
    val WHITE_CONCRETE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("white_concrete"))
    val ORANGE_CONCRETE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("orange_concrete"))
    val MAGENTA_CONCRETE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("magenta_concrete"))
    val LIGHT_BLUE_CONCRETE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_blue_concrete"))
    val YELLOW_CONCRETE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("yellow_concrete"))
    val LIME_CONCRETE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("lime_concrete"))
    val PINK_CONCRETE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("pink_concrete"))
    val GRAY_CONCRETE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("gray_concrete"))
    val LIGHT_GRAY_CONCRETE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_gray_concrete"))
    val CYAN_CONCRETE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("cyan_concrete"))
    val PURPLE_CONCRETE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("purple_concrete"))
    val BLUE_CONCRETE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("blue_concrete"))
    val BROWN_CONCRETE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("brown_concrete"))
    val GREEN_CONCRETE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("green_concrete"))
    val RED_CONCRETE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("red_concrete"))
    val BLACK_CONCRETE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("black_concrete"))
    val WHITE_CONCRETE_POWDER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("white_concrete_powder"))
    val ORANGE_CONCRETE_POWDER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("orange_concrete_powder"))
    val MAGENTA_CONCRETE_POWDER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("magenta_concrete_powder"))
    val LIGHT_BLUE_CONCRETE_POWDER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_blue_concrete_powder"))
    val YELLOW_CONCRETE_POWDER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("yellow_concrete_powder"))
    val LIME_CONCRETE_POWDER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("lime_concrete_powder"))
    val PINK_CONCRETE_POWDER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("pink_concrete_powder"))
    val GRAY_CONCRETE_POWDER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("gray_concrete_powder"))
    val LIGHT_GRAY_CONCRETE_POWDER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_gray_concrete_powder"))
    val CYAN_CONCRETE_POWDER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("cyan_concrete_powder"))
    val PURPLE_CONCRETE_POWDER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("purple_concrete_powder"))
    val BLUE_CONCRETE_POWDER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("blue_concrete_powder"))
    val BROWN_CONCRETE_POWDER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("brown_concrete_powder"))
    val GREEN_CONCRETE_POWDER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("green_concrete_powder"))
    val RED_CONCRETE_POWDER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("red_concrete_powder"))
    val BLACK_CONCRETE_POWDER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("black_concrete_powder"))
    val TURTLE_EGG: Item = Items.TURTLE_EGG
    val SNIFFER_EGG: Item = Items.SNIFFER_EGG
    val DEAD_TUBE_CORAL_BLOCK: Item = Items.DEAD_TUBE_CORAL_BLOCK
    val DEAD_BRAIN_CORAL_BLOCK: Item = Items.DEAD_BRAIN_CORAL_BLOCK
    val DEAD_BUBBLE_CORAL_BLOCK: Item = Items.DEAD_BUBBLE_CORAL_BLOCK
    val DEAD_FIRE_CORAL_BLOCK: Item = Items.DEAD_FIRE_CORAL_BLOCK
    val DEAD_HORN_CORAL_BLOCK: Item = Items.DEAD_HORN_CORAL_BLOCK
    val TUBE_CORAL_BLOCK: Item = Items.TUBE_CORAL_BLOCK
    val BRAIN_CORAL_BLOCK: Item = Items.BRAIN_CORAL_BLOCK
    val BUBBLE_CORAL_BLOCK: Item = Items.BUBBLE_CORAL_BLOCK
    val FIRE_CORAL_BLOCK: Item = Items.FIRE_CORAL_BLOCK
    val HORN_CORAL_BLOCK: Item = Items.HORN_CORAL_BLOCK
    val TUBE_CORAL: Item = Items.TUBE_CORAL
    val BRAIN_CORAL: Item = Items.BRAIN_CORAL
    val BUBBLE_CORAL: Item = Items.BUBBLE_CORAL
    val FIRE_CORAL: Item = Items.FIRE_CORAL
    val HORN_CORAL: Item = Items.HORN_CORAL
    val DEAD_BRAIN_CORAL: Item = Items.DEAD_BRAIN_CORAL
    val DEAD_BUBBLE_CORAL: Item = Items.DEAD_BUBBLE_CORAL
    val DEAD_FIRE_CORAL: Item = Items.DEAD_FIRE_CORAL
    val DEAD_HORN_CORAL: Item = Items.DEAD_HORN_CORAL
    val DEAD_TUBE_CORAL: Item = Items.DEAD_TUBE_CORAL
    val TUBE_CORAL_FAN: Item = Items.TUBE_CORAL_FAN
    val BRAIN_CORAL_FAN: Item = Items.BRAIN_CORAL_FAN
    val BUBBLE_CORAL_FAN: Item = Items.BUBBLE_CORAL_FAN
    val FIRE_CORAL_FAN: Item = Items.FIRE_CORAL_FAN
    val HORN_CORAL_FAN: Item = Items.HORN_CORAL_FAN
    val DEAD_TUBE_CORAL_FAN: Item = Items.DEAD_TUBE_CORAL_FAN
    val DEAD_BRAIN_CORAL_FAN: Item = Items.DEAD_BRAIN_CORAL_FAN
    val DEAD_BUBBLE_CORAL_FAN: Item = Items.DEAD_BUBBLE_CORAL_FAN
    val DEAD_FIRE_CORAL_FAN: Item = Items.DEAD_FIRE_CORAL_FAN
    val DEAD_HORN_CORAL_FAN: Item = Items.DEAD_HORN_CORAL_FAN
    val BLUE_ICE: Item = Items.BLUE_ICE
    val CONDUIT: Item = Items.CONDUIT
    val POLISHED_GRANITE_STAIRS: Item = Items.POLISHED_GRANITE_STAIRS
    val SMOOTH_RED_SANDSTONE_STAIRS: Item = Items.SMOOTH_RED_SANDSTONE_STAIRS
    val MOSSY_STONE_BRICK_STAIRS: Item = Items.MOSSY_STONE_BRICK_STAIRS
    val POLISHED_DIORITE_STAIRS: Item = Items.POLISHED_DIORITE_STAIRS
    val MOSSY_COBBLESTONE_STAIRS: Item = Items.MOSSY_COBBLESTONE_STAIRS
    val END_STONE_BRICK_STAIRS: Item = Items.END_STONE_BRICK_STAIRS
    val STONE_STAIRS: Item = Items.STONE_STAIRS
    val SMOOTH_SANDSTONE_STAIRS: Item = Items.SMOOTH_SANDSTONE_STAIRS
    val SMOOTH_QUARTZ_STAIRS: Item = Items.SMOOTH_QUARTZ_STAIRS
    val GRANITE_STAIRS: Item = Items.GRANITE_STAIRS
    val ANDESITE_STAIRS: Item = Items.ANDESITE_STAIRS
    val RED_NETHER_BRICK_STAIRS: Item = Items.RED_NETHER_BRICK_STAIRS
    val POLISHED_ANDESITE_STAIRS: Item = Items.POLISHED_ANDESITE_STAIRS
    val DIORITE_STAIRS: Item = Items.DIORITE_STAIRS
    val COBBLED_DEEPSLATE_STAIRS: Item = Items.COBBLED_DEEPSLATE_STAIRS
    val POLISHED_DEEPSLATE_STAIRS: Item = Items.POLISHED_DEEPSLATE_STAIRS
    val DEEPSLATE_BRICK_STAIRS: Item = Items.DEEPSLATE_BRICK_STAIRS
    val DEEPSLATE_TILE_STAIRS: Item = Items.DEEPSLATE_TILE_STAIRS
    val POLISHED_GRANITE_SLAB: Item = Items.POLISHED_GRANITE_SLAB
    val SMOOTH_RED_SANDSTONE_SLAB: Item = Items.SMOOTH_RED_SANDSTONE_SLAB
    val MOSSY_STONE_BRICK_SLAB: Item = Items.MOSSY_STONE_BRICK_SLAB
    val POLISHED_DIORITE_SLAB: Item = Items.POLISHED_DIORITE_SLAB
    val MOSSY_COBBLESTONE_SLAB: Item = Items.MOSSY_COBBLESTONE_SLAB
    val END_STONE_BRICK_SLAB: Item = Items.END_STONE_BRICK_SLAB
    val SMOOTH_SANDSTONE_SLAB: Item = Items.SMOOTH_SANDSTONE_SLAB
    val SMOOTH_QUARTZ_SLAB: Item = Items.SMOOTH_QUARTZ_SLAB
    val GRANITE_SLAB: Item = Items.GRANITE_SLAB
    val ANDESITE_SLAB: Item = Items.ANDESITE_SLAB
    val RED_NETHER_BRICK_SLAB: Item = Items.RED_NETHER_BRICK_SLAB
    val POLISHED_ANDESITE_SLAB: Item = Items.POLISHED_ANDESITE_SLAB
    val DIORITE_SLAB: Item = Items.DIORITE_SLAB
    val COBBLED_DEEPSLATE_SLAB: Item = Items.COBBLED_DEEPSLATE_SLAB
    val POLISHED_DEEPSLATE_SLAB: Item = Items.POLISHED_DEEPSLATE_SLAB
    val DEEPSLATE_BRICK_SLAB: Item = Items.DEEPSLATE_BRICK_SLAB
    val DEEPSLATE_TILE_SLAB: Item = Items.DEEPSLATE_TILE_SLAB
    val SCAFFOLDING: Item = Items.SCAFFOLDING
    val REDSTONE: Item = Items.REDSTONE
    val REDSTONE_TORCH: Item = Items.REDSTONE_TORCH
    val REDSTONE_BLOCK: Item = Items.REDSTONE_BLOCK
    val REPEATER: Item = Items.REPEATER
    val COMPARATOR: Item = Items.COMPARATOR
    val PISTON: Item = Items.PISTON
    val STICKY_PISTON: Item = Items.STICKY_PISTON
    val SLIME_BLOCK: Item = Items.SLIME_BLOCK
    val HONEY_BLOCK: Item = Items.HONEY_BLOCK
    val OBSERVER: Item = Items.OBSERVER
    val HOPPER: Item = Items.HOPPER
    val DISPENSER: Item = Items.DISPENSER
    val DROPPER: Item = Items.DROPPER
    val LECTERN: Item = Items.LECTERN
    val TARGET: Item = Items.TARGET
    val LEVER: Item = Items.LEVER
    val LIGHTNING_ROD: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("lightning_rod"))
    val DAYLIGHT_DETECTOR: Item = Items.DAYLIGHT_DETECTOR
    val SCULK_SENSOR: Item = Items.SCULK_SENSOR
    val CALIBRATED_SCULK_SENSOR: Item = Items.CALIBRATED_SCULK_SENSOR
    val TRIPWIRE_HOOK: Item = Items.TRIPWIRE_HOOK
    val TRAPPED_CHEST: Item = Items.TRAPPED_CHEST
    val TNT: Item = Items.TNT
    val REDSTONE_LAMP: Item = Items.REDSTONE_LAMP
    val NOTE_BLOCK: Item = Items.NOTE_BLOCK
    val STONE_BUTTON: Item = Items.STONE_BUTTON
    val POLISHED_BLACKSTONE_BUTTON: Item = Items.POLISHED_BLACKSTONE_BUTTON
    val OAK_BUTTON: Item = Items.OAK_BUTTON
    val SPRUCE_BUTTON: Item = Items.SPRUCE_BUTTON
    val BIRCH_BUTTON: Item = Items.BIRCH_BUTTON
    val JUNGLE_BUTTON: Item = Items.JUNGLE_BUTTON
    val ACACIA_BUTTON: Item = Items.ACACIA_BUTTON
    val CHERRY_BUTTON: Item = Items.CHERRY_BUTTON
    val DARK_OAK_BUTTON: Item = Items.DARK_OAK_BUTTON
    val PALE_OAK_BUTTON: Item = Items.PALE_OAK_BUTTON
    val MANGROVE_BUTTON: Item = Items.MANGROVE_BUTTON
    val BAMBOO_BUTTON: Item = Items.BAMBOO_BUTTON
    val CRIMSON_BUTTON: Item = Items.CRIMSON_BUTTON
    val WARPED_BUTTON: Item = Items.WARPED_BUTTON
    val STONE_PRESSURE_PLATE: Item = Items.STONE_PRESSURE_PLATE
    val POLISHED_BLACKSTONE_PRESSURE_PLATE: Item = Items.POLISHED_BLACKSTONE_PRESSURE_PLATE
    val LIGHT_WEIGHTED_PRESSURE_PLATE: Item = Items.LIGHT_WEIGHTED_PRESSURE_PLATE
    val HEAVY_WEIGHTED_PRESSURE_PLATE: Item = Items.HEAVY_WEIGHTED_PRESSURE_PLATE
    val OAK_PRESSURE_PLATE: Item = Items.OAK_PRESSURE_PLATE
    val SPRUCE_PRESSURE_PLATE: Item = Items.SPRUCE_PRESSURE_PLATE
    val BIRCH_PRESSURE_PLATE: Item = Items.BIRCH_PRESSURE_PLATE
    val JUNGLE_PRESSURE_PLATE: Item = Items.JUNGLE_PRESSURE_PLATE
    val ACACIA_PRESSURE_PLATE: Item = Items.ACACIA_PRESSURE_PLATE
    val CHERRY_PRESSURE_PLATE: Item = Items.CHERRY_PRESSURE_PLATE
    val DARK_OAK_PRESSURE_PLATE: Item = Items.DARK_OAK_PRESSURE_PLATE
    val PALE_OAK_PRESSURE_PLATE: Item = Items.PALE_OAK_PRESSURE_PLATE
    val MANGROVE_PRESSURE_PLATE: Item = Items.MANGROVE_PRESSURE_PLATE
    val BAMBOO_PRESSURE_PLATE: Item = Items.BAMBOO_PRESSURE_PLATE
    val CRIMSON_PRESSURE_PLATE: Item = Items.CRIMSON_PRESSURE_PLATE
    val WARPED_PRESSURE_PLATE: Item = Items.WARPED_PRESSURE_PLATE
    val IRON_DOOR: Item = Items.IRON_DOOR
    val OAK_DOOR: Item = Items.OAK_DOOR
    val SPRUCE_DOOR: Item = Items.SPRUCE_DOOR
    val BIRCH_DOOR: Item = Items.BIRCH_DOOR
    val JUNGLE_DOOR: Item = Items.JUNGLE_DOOR
    val ACACIA_DOOR: Item = Items.ACACIA_DOOR
    val CHERRY_DOOR: Item = Items.CHERRY_DOOR
    val DARK_OAK_DOOR: Item = Items.DARK_OAK_DOOR
    val PALE_OAK_DOOR: Item = Items.PALE_OAK_DOOR
    val MANGROVE_DOOR: Item = Items.MANGROVE_DOOR
    val BAMBOO_DOOR: Item = Items.BAMBOO_DOOR
    val CRIMSON_DOOR: Item = Items.CRIMSON_DOOR
    val WARPED_DOOR: Item = Items.WARPED_DOOR
    val COPPER_DOOR: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("copper_door"))
    val EXPOSED_COPPER_DOOR: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("exposed_copper_door"))
    val WEATHERED_COPPER_DOOR: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("weathered_copper_door"))
    val OXIDIZED_COPPER_DOOR: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("oxidized_copper_door"))
    val WAXED_COPPER_DOOR: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_copper_door"))
    val WAXED_EXPOSED_COPPER_DOOR: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_exposed_copper_door"))
    val WAXED_WEATHERED_COPPER_DOOR: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_weathered_copper_door"))
    val WAXED_OXIDIZED_COPPER_DOOR: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_oxidized_copper_door"))
    val IRON_TRAPDOOR: Item = Items.IRON_TRAPDOOR
    val OAK_TRAPDOOR: Item = Items.OAK_TRAPDOOR
    val SPRUCE_TRAPDOOR: Item = Items.SPRUCE_TRAPDOOR
    val BIRCH_TRAPDOOR: Item = Items.BIRCH_TRAPDOOR
    val JUNGLE_TRAPDOOR: Item = Items.JUNGLE_TRAPDOOR
    val ACACIA_TRAPDOOR: Item = Items.ACACIA_TRAPDOOR
    val CHERRY_TRAPDOOR: Item = Items.CHERRY_TRAPDOOR
    val DARK_OAK_TRAPDOOR: Item = Items.DARK_OAK_TRAPDOOR
    val PALE_OAK_TRAPDOOR: Item = Items.PALE_OAK_TRAPDOOR
    val MANGROVE_TRAPDOOR: Item = Items.MANGROVE_TRAPDOOR
    val BAMBOO_TRAPDOOR: Item = Items.BAMBOO_TRAPDOOR
    val CRIMSON_TRAPDOOR: Item = Items.CRIMSON_TRAPDOOR
    val WARPED_TRAPDOOR: Item = Items.WARPED_TRAPDOOR
    val COPPER_TRAPDOOR: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("copper_trapdoor"))
    val EXPOSED_COPPER_TRAPDOOR: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("exposed_copper_trapdoor"))
    val WEATHERED_COPPER_TRAPDOOR: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("weathered_copper_trapdoor"))
    val OXIDIZED_COPPER_TRAPDOOR: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("oxidized_copper_trapdoor"))
    val WAXED_COPPER_TRAPDOOR: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_copper_trapdoor"))
    val WAXED_EXPOSED_COPPER_TRAPDOOR: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_exposed_copper_trapdoor"))
    val WAXED_WEATHERED_COPPER_TRAPDOOR: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_weathered_copper_trapdoor"))
    val WAXED_OXIDIZED_COPPER_TRAPDOOR: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_oxidized_copper_trapdoor"))
    val OAK_FENCE_GATE: Item = Items.OAK_FENCE_GATE
    val SPRUCE_FENCE_GATE: Item = Items.SPRUCE_FENCE_GATE
    val BIRCH_FENCE_GATE: Item = Items.BIRCH_FENCE_GATE
    val JUNGLE_FENCE_GATE: Item = Items.JUNGLE_FENCE_GATE
    val ACACIA_FENCE_GATE: Item = Items.ACACIA_FENCE_GATE
    val CHERRY_FENCE_GATE: Item = Items.CHERRY_FENCE_GATE
    val DARK_OAK_FENCE_GATE: Item = Items.DARK_OAK_FENCE_GATE
    val PALE_OAK_FENCE_GATE: Item = Items.PALE_OAK_FENCE_GATE
    val MANGROVE_FENCE_GATE: Item = Items.MANGROVE_FENCE_GATE
    val BAMBOO_FENCE_GATE: Item = Items.BAMBOO_FENCE_GATE
    val CRIMSON_FENCE_GATE: Item = Items.CRIMSON_FENCE_GATE
    val WARPED_FENCE_GATE: Item = Items.WARPED_FENCE_GATE
    val POWERED_RAIL: Item = Items.POWERED_RAIL
    val DETECTOR_RAIL: Item = Items.DETECTOR_RAIL
    val RAIL: Item = Items.RAIL
    val ACTIVATOR_RAIL: Item = Items.ACTIVATOR_RAIL
    val SADDLE: Item = Items.SADDLE
    val MINECART: Item = Items.MINECART
    val CHEST_MINECART: Item = Items.CHEST_MINECART
    val FURNACE_MINECART: Item = Items.FURNACE_MINECART
    val TNT_MINECART: Item = Items.TNT_MINECART
    val HOPPER_MINECART: Item = Items.HOPPER_MINECART
    val CARROT_ON_A_STICK: Item = Items.CARROT_ON_A_STICK
    val WARPED_FUNGUS_ON_A_STICK: Item = Items.WARPED_FUNGUS_ON_A_STICK
    val PHANTOM_MEMBRANE: Item = Items.PHANTOM_MEMBRANE
    val ELYTRA: Item = Items.ELYTRA
    val OAK_BOAT: Item = Items.OAK_BOAT
    val OAK_CHEST_BOAT: Item = Items.OAK_CHEST_BOAT
    val SPRUCE_BOAT: Item = Items.SPRUCE_BOAT
    val SPRUCE_CHEST_BOAT: Item = Items.SPRUCE_CHEST_BOAT
    val BIRCH_BOAT: Item = Items.BIRCH_BOAT
    val BIRCH_CHEST_BOAT: Item = Items.BIRCH_CHEST_BOAT
    val JUNGLE_BOAT: Item = Items.JUNGLE_BOAT
    val JUNGLE_CHEST_BOAT: Item = Items.JUNGLE_CHEST_BOAT
    val ACACIA_BOAT: Item = Items.ACACIA_BOAT
    val ACACIA_CHEST_BOAT: Item = Items.ACACIA_CHEST_BOAT
    val CHERRY_BOAT: Item = Items.CHERRY_BOAT
    val CHERRY_CHEST_BOAT: Item = Items.CHERRY_CHEST_BOAT
    val DARK_OAK_BOAT: Item = Items.DARK_OAK_BOAT
    val DARK_OAK_CHEST_BOAT: Item = Items.DARK_OAK_CHEST_BOAT
    val PALE_OAK_BOAT: Item = Items.PALE_OAK_BOAT
    val PALE_OAK_CHEST_BOAT: Item = Items.PALE_OAK_CHEST_BOAT
    val MANGROVE_BOAT: Item = Items.MANGROVE_BOAT
    val MANGROVE_CHEST_BOAT: Item = Items.MANGROVE_CHEST_BOAT
    val BAMBOO_RAFT: Item = Items.BAMBOO_RAFT
    val BAMBOO_CHEST_RAFT: Item = Items.BAMBOO_CHEST_RAFT
    val STRUCTURE_BLOCK: Item = Items.STRUCTURE_BLOCK
    val JIGSAW: Item = Items.JIGSAW
    val TURTLE_HELMET: Item = Items.TURTLE_HELMET
    val TURTLE_SCUTE: Item = Items.TURTLE_SCUTE
    val ARMADILLO_SCUTE: Item = Items.ARMADILLO_SCUTE
    val WOLF_ARMOR: Item = Items.WOLF_ARMOR
    val FLINT_AND_STEEL: Item = Items.FLINT_AND_STEEL
    val BOWL: Item = Items.BOWL
    val APPLE: Item = Items.APPLE
    val BOW: Item = Items.BOW
    val ARROW: Item = Items.ARROW
    val COAL: Item = Items.COAL
    val CHARCOAL: Item = Items.CHARCOAL
    val DIAMOND: Item = Items.DIAMOND
    val EMERALD: Item = Items.EMERALD
    val LAPIS_LAZULI: Item = Items.LAPIS_LAZULI
    val QUARTZ: Item = Items.QUARTZ
    val AMETHYST_SHARD: Item = Items.AMETHYST_SHARD
    val RAW_IRON: Item = Items.RAW_IRON
    val IRON_INGOT: Item = Items.IRON_INGOT
    val RAW_COPPER: Item = Items.RAW_COPPER
    val COPPER_INGOT: Item = Items.COPPER_INGOT
    val RAW_GOLD: Item = Items.RAW_GOLD
    val GOLD_INGOT: Item = Items.GOLD_INGOT
    val NETHERITE_INGOT: Item = Items.NETHERITE_INGOT
    val NETHERITE_SCRAP: Item = Items.NETHERITE_SCRAP
    val WOODEN_SWORD: Item = Items.WOODEN_SWORD
    val WOODEN_SHOVEL: Item = Items.WOODEN_SHOVEL
    val WOODEN_PICKAXE: Item = Items.WOODEN_PICKAXE
    val WOODEN_AXE: Item = Items.WOODEN_AXE
    val WOODEN_HOE: Item = Items.WOODEN_HOE
    val STONE_SWORD: Item = Items.STONE_SWORD
    val STONE_SHOVEL: Item = Items.STONE_SHOVEL
    val STONE_PICKAXE: Item = Items.STONE_PICKAXE
    val STONE_AXE: Item = Items.STONE_AXE
    val STONE_HOE: Item = Items.STONE_HOE
    val GOLDEN_SWORD: Item = Items.GOLDEN_SWORD
    val GOLDEN_SHOVEL: Item = Items.GOLDEN_SHOVEL
    val GOLDEN_PICKAXE: Item = Items.GOLDEN_PICKAXE
    val GOLDEN_AXE: Item = Items.GOLDEN_AXE
    val GOLDEN_HOE: Item = Items.GOLDEN_HOE
    val IRON_SWORD: Item = Items.IRON_SWORD
    val IRON_SHOVEL: Item = Items.IRON_SHOVEL
    val IRON_PICKAXE: Item = Items.IRON_PICKAXE
    val IRON_AXE: Item = Items.IRON_AXE
    val IRON_HOE: Item = Items.IRON_HOE
    val DIAMOND_SWORD: Item = Items.DIAMOND_SWORD
    val DIAMOND_SHOVEL: Item = Items.DIAMOND_SHOVEL
    val DIAMOND_PICKAXE: Item = Items.DIAMOND_PICKAXE
    val DIAMOND_AXE: Item = Items.DIAMOND_AXE
    val DIAMOND_HOE: Item = Items.DIAMOND_HOE
    val NETHERITE_SWORD: Item = Items.NETHERITE_SWORD
    val NETHERITE_SHOVEL: Item = Items.NETHERITE_SHOVEL
    val NETHERITE_PICKAXE: Item = Items.NETHERITE_PICKAXE
    val NETHERITE_AXE: Item = Items.NETHERITE_AXE
    val NETHERITE_HOE: Item = Items.NETHERITE_HOE
    val STICK: Item = Items.STICK
    val MUSHROOM_STEW: Item = Items.MUSHROOM_STEW
    val STRING: Item = Items.STRING
    val FEATHER: Item = Items.FEATHER
    val GUNPOWDER: Item = Items.GUNPOWDER
    val WHEAT_SEEDS: Item = Items.WHEAT_SEEDS
    val WHEAT: Item = Items.WHEAT
    val BREAD: Item = Items.BREAD
    val LEATHER_HELMET: Item = Items.LEATHER_HELMET
    val LEATHER_CHESTPLATE: Item = Items.LEATHER_CHESTPLATE
    val LEATHER_LEGGINGS: Item = Items.LEATHER_LEGGINGS
    val LEATHER_BOOTS: Item = Items.LEATHER_BOOTS
    val CHAINMAIL_HELMET: Item = Items.CHAINMAIL_HELMET
    val CHAINMAIL_CHESTPLATE: Item = Items.CHAINMAIL_CHESTPLATE
    val CHAINMAIL_LEGGINGS: Item = Items.CHAINMAIL_LEGGINGS
    val CHAINMAIL_BOOTS: Item = Items.CHAINMAIL_BOOTS
    val IRON_HELMET: Item = Items.IRON_HELMET
    val IRON_CHESTPLATE: Item = Items.IRON_CHESTPLATE
    val IRON_LEGGINGS: Item = Items.IRON_LEGGINGS
    val IRON_BOOTS: Item = Items.IRON_BOOTS
    val DIAMOND_HELMET: Item = Items.DIAMOND_HELMET
    val DIAMOND_CHESTPLATE: Item = Items.DIAMOND_CHESTPLATE
    val DIAMOND_LEGGINGS: Item = Items.DIAMOND_LEGGINGS
    val DIAMOND_BOOTS: Item = Items.DIAMOND_BOOTS
    val GOLDEN_HELMET: Item = Items.GOLDEN_HELMET
    val GOLDEN_CHESTPLATE: Item = Items.GOLDEN_CHESTPLATE
    val GOLDEN_LEGGINGS: Item = Items.GOLDEN_LEGGINGS
    val GOLDEN_BOOTS: Item = Items.GOLDEN_BOOTS
    val NETHERITE_HELMET: Item = Items.NETHERITE_HELMET
    val NETHERITE_CHESTPLATE: Item = Items.NETHERITE_CHESTPLATE
    val NETHERITE_LEGGINGS: Item = Items.NETHERITE_LEGGINGS
    val NETHERITE_BOOTS: Item = Items.NETHERITE_BOOTS
    val FLINT: Item = Items.FLINT
    val PORKCHOP: Item = Items.PORKCHOP
    val COOKED_PORKCHOP: Item = Items.COOKED_PORKCHOP
    val PAINTING: Item = Items.PAINTING
    val GOLDEN_APPLE: Item = Items.GOLDEN_APPLE
    val ENCHANTED_GOLDEN_APPLE: Item = Items.ENCHANTED_GOLDEN_APPLE
    val OAK_SIGN: Item = Items.OAK_SIGN
    val SPRUCE_SIGN: Item = Items.SPRUCE_SIGN
    val BIRCH_SIGN: Item = Items.BIRCH_SIGN
    val JUNGLE_SIGN: Item = Items.JUNGLE_SIGN
    val ACACIA_SIGN: Item = Items.ACACIA_SIGN
    val CHERRY_SIGN: Item = Items.CHERRY_SIGN
    val DARK_OAK_SIGN: Item = Items.DARK_OAK_SIGN
    val PALE_OAK_SIGN: Item = Items.PALE_OAK_SIGN
    val MANGROVE_SIGN: Item = Items.MANGROVE_SIGN
    val BAMBOO_SIGN: Item = Items.BAMBOO_SIGN
    val CRIMSON_SIGN: Item = Items.CRIMSON_SIGN
    val WARPED_SIGN: Item = Items.WARPED_SIGN
    val OAK_HANGING_SIGN: Item = Items.OAK_HANGING_SIGN
    val SPRUCE_HANGING_SIGN: Item = Items.SPRUCE_HANGING_SIGN
    val BIRCH_HANGING_SIGN: Item = Items.BIRCH_HANGING_SIGN
    val JUNGLE_HANGING_SIGN: Item = Items.JUNGLE_HANGING_SIGN
    val ACACIA_HANGING_SIGN: Item = Items.ACACIA_HANGING_SIGN
    val CHERRY_HANGING_SIGN: Item = Items.CHERRY_HANGING_SIGN
    val DARK_OAK_HANGING_SIGN: Item = Items.DARK_OAK_HANGING_SIGN
    val PALE_OAK_HANGING_SIGN: Item = Items.PALE_OAK_HANGING_SIGN
    val MANGROVE_HANGING_SIGN: Item = Items.MANGROVE_HANGING_SIGN
    val BAMBOO_HANGING_SIGN: Item = Items.BAMBOO_HANGING_SIGN
    val CRIMSON_HANGING_SIGN: Item = Items.CRIMSON_HANGING_SIGN
    val WARPED_HANGING_SIGN: Item = Items.WARPED_HANGING_SIGN
    val BUCKET: Item = Items.BUCKET
    val WATER_BUCKET: Item = Items.WATER_BUCKET
    val LAVA_BUCKET: Item = Items.LAVA_BUCKET
    val POWDER_SNOW_BUCKET: Item = Items.POWDER_SNOW_BUCKET
    val SNOWBALL: Item = Items.SNOWBALL
    val LEATHER: Item = Items.LEATHER
    val MILK_BUCKET: Item = Items.MILK_BUCKET
    val PUFFERFISH_BUCKET: Item = Items.PUFFERFISH_BUCKET
    val SALMON_BUCKET: Item = Items.SALMON_BUCKET
    val COD_BUCKET: Item = Items.COD_BUCKET
    val TROPICAL_FISH_BUCKET: Item = Items.TROPICAL_FISH_BUCKET
    val AXOLOTL_BUCKET: Item = Items.AXOLOTL_BUCKET
    val TADPOLE_BUCKET: Item = Items.TADPOLE_BUCKET
    val BRICK: Item = Items.BRICK
    val CLAY_BALL: Item = Items.CLAY_BALL
    val DRIED_KELP_BLOCK: Item = Items.DRIED_KELP_BLOCK
    val PAPER: Item = Items.PAPER
    val BOOK: Item = Items.BOOK
    val SLIME_BALL: Item = Items.SLIME_BALL
    val EGG: Item = Items.EGG
    val COMPASS: Item = Items.COMPASS
    val RECOVERY_COMPASS: Item = Items.RECOVERY_COMPASS
    val BUNDLE: Item = Items.BUNDLE
    val WHITE_BUNDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("white_bundle"))
    val ORANGE_BUNDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("orange_bundle"))
    val MAGENTA_BUNDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("magenta_bundle"))
    val LIGHT_BLUE_BUNDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_blue_bundle"))
    val YELLOW_BUNDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("yellow_bundle"))
    val LIME_BUNDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("lime_bundle"))
    val PINK_BUNDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("pink_bundle"))
    val GRAY_BUNDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("gray_bundle"))
    val LIGHT_GRAY_BUNDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_gray_bundle"))
    val CYAN_BUNDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("cyan_bundle"))
    val PURPLE_BUNDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("purple_bundle"))
    val BLUE_BUNDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("blue_bundle"))
    val BROWN_BUNDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("brown_bundle"))
    val GREEN_BUNDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("green_bundle"))
    val RED_BUNDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("red_bundle"))
    val BLACK_BUNDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("black_bundle"))
    val FISHING_ROD: Item = Items.FISHING_ROD
    val CLOCK: Item = Items.CLOCK
    val SPYGLASS: Item = Items.SPYGLASS
    val GLOWSTONE_DUST: Item = Items.GLOWSTONE_DUST
    val COD: Item = Items.COD
    val SALMON: Item = Items.SALMON
    val TROPICAL_FISH: Item = Items.TROPICAL_FISH
    val PUFFERFISH: Item = Items.PUFFERFISH
    val COOKED_COD: Item = Items.COOKED_COD
    val COOKED_SALMON: Item = Items.COOKED_SALMON
    val INK_SAC: Item = Items.INK_SAC
    val GLOW_INK_SAC: Item = Items.GLOW_INK_SAC
    val COCOA_BEANS: Item = Items.COCOA_BEANS
    val WHITE_DYE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("white_dye"))
    val ORANGE_DYE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("orange_dye"))
    val MAGENTA_DYE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("magenta_dye"))
    val LIGHT_BLUE_DYE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_blue_dye"))
    val YELLOW_DYE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("yellow_dye"))
    val LIME_DYE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("lime_dye"))
    val PINK_DYE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("pink_dye"))
    val GRAY_DYE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("gray_dye"))
    val LIGHT_GRAY_DYE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_gray_dye"))
    val CYAN_DYE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("cyan_dye"))
    val PURPLE_DYE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("purple_dye"))
    val BLUE_DYE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("blue_dye"))
    val BROWN_DYE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("brown_dye"))
    val GREEN_DYE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("green_dye"))
    val RED_DYE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("red_dye"))
    val BLACK_DYE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("black_dye"))
    val BONE_MEAL: Item = Items.BONE_MEAL
    val BONE: Item = Items.BONE
    val SUGAR: Item = Items.SUGAR
    val CAKE: Item = Items.CAKE
    val WHITE_BED: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("white_bed"))
    val ORANGE_BED: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("orange_bed"))
    val MAGENTA_BED: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("magenta_bed"))
    val LIGHT_BLUE_BED: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_blue_bed"))
    val YELLOW_BED: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("yellow_bed"))
    val LIME_BED: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("lime_bed"))
    val PINK_BED: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("pink_bed"))
    val GRAY_BED: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("gray_bed"))
    val LIGHT_GRAY_BED: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_gray_bed"))
    val CYAN_BED: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("cyan_bed"))
    val PURPLE_BED: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("purple_bed"))
    val BLUE_BED: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("blue_bed"))
    val BROWN_BED: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("brown_bed"))
    val GREEN_BED: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("green_bed"))
    val RED_BED: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("red_bed"))
    val BLACK_BED: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("black_bed"))
    val COOKIE: Item = Items.COOKIE
    val CRAFTER: Item = Items.CRAFTER
    val FILLED_MAP: Item = Items.FILLED_MAP
    val SHEARS: Item = Items.SHEARS
    val MELON_SLICE: Item = Items.MELON_SLICE
    val DRIED_KELP: Item = Items.DRIED_KELP
    val PUMPKIN_SEEDS: Item = Items.PUMPKIN_SEEDS
    val MELON_SEEDS: Item = Items.MELON_SEEDS
    val BEEF: Item = Items.BEEF
    val COOKED_BEEF: Item = Items.COOKED_BEEF
    val CHICKEN: Item = Items.CHICKEN
    val COOKED_CHICKEN: Item = Items.COOKED_CHICKEN
    val ROTTEN_FLESH: Item = Items.ROTTEN_FLESH
    val ENDER_PEARL: Item = Items.ENDER_PEARL
    val BLAZE_ROD: Item = Items.BLAZE_ROD
    val GHAST_TEAR: Item = Items.GHAST_TEAR
    val GOLD_NUGGET: Item = Items.GOLD_NUGGET
    val NETHER_WART: Item = Items.NETHER_WART
    val GLASS_BOTTLE: Item = Items.GLASS_BOTTLE
    val POTION: Item = Items.POTION
    val SPIDER_EYE: Item = Items.SPIDER_EYE
    val FERMENTED_SPIDER_EYE: Item = Items.FERMENTED_SPIDER_EYE
    val BLAZE_POWDER: Item = Items.BLAZE_POWDER
    val MAGMA_CREAM: Item = Items.MAGMA_CREAM
    val BREWING_STAND: Item = Items.BREWING_STAND
    val CAULDRON: Item = Items.CAULDRON
    val ENDER_EYE: Item = Items.ENDER_EYE
    val GLISTERING_MELON_SLICE: Item = Items.GLISTERING_MELON_SLICE
    val ARMADILLO_SPAWN_EGG: Item = Items.ARMADILLO_SPAWN_EGG
    val ALLAY_SPAWN_EGG: Item = Items.ALLAY_SPAWN_EGG
    val AXOLOTL_SPAWN_EGG: Item = Items.AXOLOTL_SPAWN_EGG
    val BAT_SPAWN_EGG: Item = Items.BAT_SPAWN_EGG
    val BEE_SPAWN_EGG: Item = Items.BEE_SPAWN_EGG
    val BLAZE_SPAWN_EGG: Item = Items.BLAZE_SPAWN_EGG
    val BOGGED_SPAWN_EGG: Item = Items.BOGGED_SPAWN_EGG
    val BREEZE_SPAWN_EGG: Item = Items.BREEZE_SPAWN_EGG
    val CAT_SPAWN_EGG: Item = Items.CAT_SPAWN_EGG
    val CAMEL_SPAWN_EGG: Item = Items.CAMEL_SPAWN_EGG
    val CAVE_SPIDER_SPAWN_EGG: Item = Items.CAVE_SPIDER_SPAWN_EGG
    val CHICKEN_SPAWN_EGG: Item = Items.CHICKEN_SPAWN_EGG
    val COD_SPAWN_EGG: Item = Items.COD_SPAWN_EGG
    val COW_SPAWN_EGG: Item = Items.COW_SPAWN_EGG
    val CREEPER_SPAWN_EGG: Item = Items.CREEPER_SPAWN_EGG
    val DOLPHIN_SPAWN_EGG: Item = Items.DOLPHIN_SPAWN_EGG
    val DONKEY_SPAWN_EGG: Item = Items.DONKEY_SPAWN_EGG
    val DROWNED_SPAWN_EGG: Item = Items.DROWNED_SPAWN_EGG
    val ELDER_GUARDIAN_SPAWN_EGG: Item = Items.ELDER_GUARDIAN_SPAWN_EGG
    val ENDER_DRAGON_SPAWN_EGG: Item = Items.ENDER_DRAGON_SPAWN_EGG
    val ENDERMAN_SPAWN_EGG: Item = Items.ENDERMAN_SPAWN_EGG
    val ENDERMITE_SPAWN_EGG: Item = Items.ENDERMITE_SPAWN_EGG
    val EVOKER_SPAWN_EGG: Item = Items.EVOKER_SPAWN_EGG
    val FOX_SPAWN_EGG: Item = Items.FOX_SPAWN_EGG
    val FROG_SPAWN_EGG: Item = Items.FROG_SPAWN_EGG
    val GHAST_SPAWN_EGG: Item = Items.GHAST_SPAWN_EGG
    val GLOW_SQUID_SPAWN_EGG: Item = Items.GLOW_SQUID_SPAWN_EGG
    val GOAT_SPAWN_EGG: Item = Items.GOAT_SPAWN_EGG
    val GUARDIAN_SPAWN_EGG: Item = Items.GUARDIAN_SPAWN_EGG
    val HOGLIN_SPAWN_EGG: Item = Items.HOGLIN_SPAWN_EGG
    val HORSE_SPAWN_EGG: Item = Items.HORSE_SPAWN_EGG
    val HUSK_SPAWN_EGG: Item = Items.HUSK_SPAWN_EGG
    val IRON_GOLEM_SPAWN_EGG: Item = Items.IRON_GOLEM_SPAWN_EGG
    val LLAMA_SPAWN_EGG: Item = Items.LLAMA_SPAWN_EGG
    val MAGMA_CUBE_SPAWN_EGG: Item = Items.MAGMA_CUBE_SPAWN_EGG
    val MOOSHROOM_SPAWN_EGG: Item = Items.MOOSHROOM_SPAWN_EGG
    val MULE_SPAWN_EGG: Item = Items.MULE_SPAWN_EGG
    val OCELOT_SPAWN_EGG: Item = Items.OCELOT_SPAWN_EGG
    val PANDA_SPAWN_EGG: Item = Items.PANDA_SPAWN_EGG
    val PARROT_SPAWN_EGG: Item = Items.PARROT_SPAWN_EGG
    val PHANTOM_SPAWN_EGG: Item = Items.PHANTOM_SPAWN_EGG
    val PIG_SPAWN_EGG: Item = Items.PIG_SPAWN_EGG
    val PIGLIN_SPAWN_EGG: Item = Items.PIGLIN_SPAWN_EGG
    val PIGLIN_BRUTE_SPAWN_EGG: Item = Items.PIGLIN_BRUTE_SPAWN_EGG
    val PILLAGER_SPAWN_EGG: Item = Items.PILLAGER_SPAWN_EGG
    val POLAR_BEAR_SPAWN_EGG: Item = Items.POLAR_BEAR_SPAWN_EGG
    val PUFFERFISH_SPAWN_EGG: Item = Items.PUFFERFISH_SPAWN_EGG
    val RABBIT_SPAWN_EGG: Item = Items.RABBIT_SPAWN_EGG
    val RAVAGER_SPAWN_EGG: Item = Items.RAVAGER_SPAWN_EGG
    val SALMON_SPAWN_EGG: Item = Items.SALMON_SPAWN_EGG
    val SHEEP_SPAWN_EGG: Item = Items.SHEEP_SPAWN_EGG
    val SHULKER_SPAWN_EGG: Item = Items.SHULKER_SPAWN_EGG
    val SILVERFISH_SPAWN_EGG: Item = Items.SILVERFISH_SPAWN_EGG
    val SKELETON_SPAWN_EGG: Item = Items.SKELETON_SPAWN_EGG
    val SKELETON_HORSE_SPAWN_EGG: Item = Items.SKELETON_HORSE_SPAWN_EGG
    val SLIME_SPAWN_EGG: Item = Items.SLIME_SPAWN_EGG
    val SNIFFER_SPAWN_EGG: Item = Items.SNIFFER_SPAWN_EGG
    val SNOW_GOLEM_SPAWN_EGG: Item = Items.SNOW_GOLEM_SPAWN_EGG
    val SPIDER_SPAWN_EGG: Item = Items.SPIDER_SPAWN_EGG
    val SQUID_SPAWN_EGG: Item = Items.SQUID_SPAWN_EGG
    val STRAY_SPAWN_EGG: Item = Items.STRAY_SPAWN_EGG
    val STRIDER_SPAWN_EGG: Item = Items.STRIDER_SPAWN_EGG
    val TADPOLE_SPAWN_EGG: Item = Items.TADPOLE_SPAWN_EGG
    val TRADER_LLAMA_SPAWN_EGG: Item = Items.TRADER_LLAMA_SPAWN_EGG
    val TROPICAL_FISH_SPAWN_EGG: Item = Items.TROPICAL_FISH_SPAWN_EGG
    val TURTLE_SPAWN_EGG: Item = Items.TURTLE_SPAWN_EGG
    val VEX_SPAWN_EGG: Item = Items.VEX_SPAWN_EGG
    val VILLAGER_SPAWN_EGG: Item = Items.VILLAGER_SPAWN_EGG
    val VINDICATOR_SPAWN_EGG: Item = Items.VINDICATOR_SPAWN_EGG
    val WANDERING_TRADER_SPAWN_EGG: Item = Items.WANDERING_TRADER_SPAWN_EGG
    val WARDEN_SPAWN_EGG: Item = Items.WARDEN_SPAWN_EGG
    val WITCH_SPAWN_EGG: Item = Items.WITCH_SPAWN_EGG
    val WITHER_SPAWN_EGG: Item = Items.WITHER_SPAWN_EGG
    val WITHER_SKELETON_SPAWN_EGG: Item = Items.WITHER_SKELETON_SPAWN_EGG
    val WOLF_SPAWN_EGG: Item = Items.WOLF_SPAWN_EGG
    val ZOGLIN_SPAWN_EGG: Item = Items.ZOGLIN_SPAWN_EGG
    val CREAKING_SPAWN_EGG: Item = Items.CREAKING_SPAWN_EGG
    val ZOMBIE_SPAWN_EGG: Item = Items.ZOMBIE_SPAWN_EGG
    val ZOMBIE_HORSE_SPAWN_EGG: Item = Items.ZOMBIE_HORSE_SPAWN_EGG
    val ZOMBIE_VILLAGER_SPAWN_EGG: Item = Items.ZOMBIE_VILLAGER_SPAWN_EGG
    val ZOMBIFIED_PIGLIN_SPAWN_EGG: Item = Items.ZOMBIFIED_PIGLIN_SPAWN_EGG
    val EXPERIENCE_BOTTLE: Item = Items.EXPERIENCE_BOTTLE
    val FIRE_CHARGE: Item = Items.FIRE_CHARGE
    val WIND_CHARGE: Item = Items.WIND_CHARGE
    val WRITABLE_BOOK: Item = Items.WRITABLE_BOOK
    val WRITTEN_BOOK: Item = Items.WRITTEN_BOOK
    val BREEZE_ROD: Item = Items.BREEZE_ROD
    val MACE: Item = Items.MACE
    val ITEM_FRAME: Item = Items.ITEM_FRAME
    val GLOW_ITEM_FRAME: Item = Items.GLOW_ITEM_FRAME
    val FLOWER_POT: Item = Items.FLOWER_POT
    val CARROT: Item = Items.CARROT
    val POTATO: Item = Items.POTATO
    val BAKED_POTATO: Item = Items.BAKED_POTATO
    val POISONOUS_POTATO: Item = Items.POISONOUS_POTATO
    val MAP: Item = Items.MAP
    val GOLDEN_CARROT: Item = Items.GOLDEN_CARROT
    val SKELETON_SKULL: Item = Items.SKELETON_SKULL
    val WITHER_SKELETON_SKULL: Item = Items.WITHER_SKELETON_SKULL
    val PLAYER_HEAD: Item = Items.PLAYER_HEAD
    val ZOMBIE_HEAD: Item = Items.ZOMBIE_HEAD
    val CREEPER_HEAD: Item = Items.CREEPER_HEAD
    val DRAGON_HEAD: Item = Items.DRAGON_HEAD
    val PIGLIN_HEAD: Item = Items.PIGLIN_HEAD
    val NETHER_STAR: Item = Items.NETHER_STAR
    val PUMPKIN_PIE: Item = Items.PUMPKIN_PIE
    val FIREWORK_ROCKET: Item = Items.FIREWORK_ROCKET
    val FIREWORK_STAR: Item = Items.FIREWORK_STAR
    val ENCHANTED_BOOK: Item = Items.ENCHANTED_BOOK
    val NETHER_BRICK: Item = Items.NETHER_BRICK
    val RESIN_BRICK: Item = Items.RESIN_BRICK
    val PRISMARINE_SHARD: Item = Items.PRISMARINE_SHARD
    val PRISMARINE_CRYSTALS: Item = Items.PRISMARINE_CRYSTALS
    val RABBIT: Item = Items.RABBIT
    val COOKED_RABBIT: Item = Items.COOKED_RABBIT
    val RABBIT_STEW: Item = Items.RABBIT_STEW
    val RABBIT_FOOT: Item = Items.RABBIT_FOOT
    val RABBIT_HIDE: Item = Items.RABBIT_HIDE
    val ARMOR_STAND: Item = Items.ARMOR_STAND
    val IRON_HORSE_ARMOR: Item = Items.IRON_HORSE_ARMOR
    val GOLDEN_HORSE_ARMOR: Item = Items.GOLDEN_HORSE_ARMOR
    val DIAMOND_HORSE_ARMOR: Item = Items.DIAMOND_HORSE_ARMOR
    val LEATHER_HORSE_ARMOR: Item = Items.LEATHER_HORSE_ARMOR
    val LEAD: Item = Items.LEAD
    val NAME_TAG: Item = Items.NAME_TAG
    val COMMAND_BLOCK_MINECART: Item = Items.COMMAND_BLOCK_MINECART
    val MUTTON: Item = Items.MUTTON
    val COOKED_MUTTON: Item = Items.COOKED_MUTTON
    val WHITE_BANNER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("white_banner"))
    val ORANGE_BANNER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("orange_banner"))
    val MAGENTA_BANNER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("magenta_banner"))
    val LIGHT_BLUE_BANNER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_blue_banner"))
    val YELLOW_BANNER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("yellow_banner"))
    val LIME_BANNER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("lime_banner"))
    val PINK_BANNER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("pink_banner"))
    val GRAY_BANNER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("gray_banner"))
    val LIGHT_GRAY_BANNER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_gray_banner"))
    val CYAN_BANNER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("cyan_banner"))
    val PURPLE_BANNER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("purple_banner"))
    val BLUE_BANNER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("blue_banner"))
    val BROWN_BANNER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("brown_banner"))
    val GREEN_BANNER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("green_banner"))
    val RED_BANNER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("red_banner"))
    val BLACK_BANNER: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("black_banner"))
    val END_CRYSTAL: Item = Items.END_CRYSTAL
    val CHORUS_FRUIT: Item = Items.CHORUS_FRUIT
    val POPPED_CHORUS_FRUIT: Item = Items.POPPED_CHORUS_FRUIT
    val TORCHFLOWER_SEEDS: Item = Items.TORCHFLOWER_SEEDS
    val PITCHER_POD: Item = Items.PITCHER_POD
    val BEETROOT: Item = Items.BEETROOT
    val BEETROOT_SEEDS: Item = Items.BEETROOT_SEEDS
    val BEETROOT_SOUP: Item = Items.BEETROOT_SOUP
    val DRAGON_BREATH: Item = Items.DRAGON_BREATH
    val SPLASH_POTION: Item = Items.SPLASH_POTION
    val SPECTRAL_ARROW: Item = Items.SPECTRAL_ARROW
    val TIPPED_ARROW: Item = Items.TIPPED_ARROW
    val LINGERING_POTION: Item = Items.LINGERING_POTION
    val SHIELD: Item = Items.SHIELD
    val TOTEM_OF_UNDYING: Item = Items.TOTEM_OF_UNDYING
    val SHULKER_SHELL: Item = Items.SHULKER_SHELL
    val IRON_NUGGET: Item = Items.IRON_NUGGET
    val KNOWLEDGE_BOOK: Item = Items.KNOWLEDGE_BOOK
    val DEBUG_STICK: Item = Items.DEBUG_STICK
    val MUSIC_DISC_13: Item = Items.MUSIC_DISC_13
    val MUSIC_DISC_CAT: Item = Items.MUSIC_DISC_CAT
    val MUSIC_DISC_BLOCKS: Item = Items.MUSIC_DISC_BLOCKS
    val MUSIC_DISC_CHIRP: Item = Items.MUSIC_DISC_CHIRP
    val MUSIC_DISC_CREATOR: Item = Items.MUSIC_DISC_CREATOR
    val MUSIC_DISC_CREATOR_MUSIC_BOX: Item = Items.MUSIC_DISC_CREATOR_MUSIC_BOX
    val MUSIC_DISC_FAR: Item = Items.MUSIC_DISC_FAR
    val MUSIC_DISC_MALL: Item = Items.MUSIC_DISC_MALL
    val MUSIC_DISC_MELLOHI: Item = Items.MUSIC_DISC_MELLOHI
    val MUSIC_DISC_STAL: Item = Items.MUSIC_DISC_STAL
    val MUSIC_DISC_STRAD: Item = Items.MUSIC_DISC_STRAD
    val MUSIC_DISC_WARD: Item = Items.MUSIC_DISC_WARD
    val MUSIC_DISC_11: Item = Items.MUSIC_DISC_11
    val MUSIC_DISC_WAIT: Item = Items.MUSIC_DISC_WAIT
    val MUSIC_DISC_OTHERSIDE: Item = Items.MUSIC_DISC_OTHERSIDE
    val MUSIC_DISC_RELIC: Item = Items.MUSIC_DISC_RELIC
    val MUSIC_DISC_5: Item = Items.MUSIC_DISC_5
    val MUSIC_DISC_PIGSTEP: Item = Items.MUSIC_DISC_PIGSTEP
    val MUSIC_DISC_PRECIPICE: Item = Items.MUSIC_DISC_PRECIPICE
    val DISC_FRAGMENT_5: Item = Items.DISC_FRAGMENT_5
    val TRIDENT: Item = Items.TRIDENT
    val NAUTILUS_SHELL: Item = Items.NAUTILUS_SHELL
    val HEART_OF_THE_SEA: Item = Items.HEART_OF_THE_SEA
    val CROSSBOW: Item = Items.CROSSBOW
    val SUSPICIOUS_STEW: Item = Items.SUSPICIOUS_STEW
    val LOOM: Item = Items.LOOM
    val FLOWER_BANNER_PATTERN: Item = Items.FLOWER_BANNER_PATTERN
    val CREEPER_BANNER_PATTERN: Item = Items.CREEPER_BANNER_PATTERN
    val SKULL_BANNER_PATTERN: Item = Items.SKULL_BANNER_PATTERN
    val MOJANG_BANNER_PATTERN: Item = Items.MOJANG_BANNER_PATTERN
    val GLOBE_BANNER_PATTERN: Item = Items.GLOBE_BANNER_PATTERN
    val PIGLIN_BANNER_PATTERN: Item = Items.PIGLIN_BANNER_PATTERN
    val FLOW_BANNER_PATTERN: Item = Items.FLOW_BANNER_PATTERN
    val GUSTER_BANNER_PATTERN: Item = Items.GUSTER_BANNER_PATTERN
    val FIELD_MASONED_BANNER_PATTERN: Item = Items.FIELD_MASONED_BANNER_PATTERN
    val BORDURE_INDENTED_BANNER_PATTERN: Item = Items.BORDURE_INDENTED_BANNER_PATTERN
    val GOAT_HORN: Item = Items.GOAT_HORN
    val COMPOSTER: Item = Items.COMPOSTER
    val BARREL: Item = Items.BARREL
    val SMOKER: Item = Items.SMOKER
    val BLAST_FURNACE: Item = Items.BLAST_FURNACE
    val CARTOGRAPHY_TABLE: Item = Items.CARTOGRAPHY_TABLE
    val FLETCHING_TABLE: Item = Items.FLETCHING_TABLE
    val GRINDSTONE: Item = Items.GRINDSTONE
    val SMITHING_TABLE: Item = Items.SMITHING_TABLE
    val STONECUTTER: Item = Items.STONECUTTER
    val BELL: Item = Items.BELL
    val LANTERN: Item = Items.LANTERN
    val SOUL_LANTERN: Item = Items.SOUL_LANTERN
    val SWEET_BERRIES: Item = Items.SWEET_BERRIES
    val GLOW_BERRIES: Item = Items.GLOW_BERRIES
    val CAMPFIRE: Item = Items.CAMPFIRE
    val SOUL_CAMPFIRE: Item = Items.SOUL_CAMPFIRE
    val SHROOMLIGHT: Item = Items.SHROOMLIGHT
    val HONEYCOMB: Item = Items.HONEYCOMB
    val BEE_NEST: Item = Items.BEE_NEST
    val BEEHIVE: Item = Items.BEEHIVE
    val HONEY_BOTTLE: Item = Items.HONEY_BOTTLE
    val HONEYCOMB_BLOCK: Item = Items.HONEYCOMB_BLOCK
    val LODESTONE: Item = Items.LODESTONE
    val CRYING_OBSIDIAN: Item = Items.CRYING_OBSIDIAN
    val BLACKSTONE: Item = Items.BLACKSTONE
    val BLACKSTONE_SLAB: Item = Items.BLACKSTONE_SLAB
    val BLACKSTONE_STAIRS: Item = Items.BLACKSTONE_STAIRS
    val GILDED_BLACKSTONE: Item = Items.GILDED_BLACKSTONE
    val POLISHED_BLACKSTONE: Item = Items.POLISHED_BLACKSTONE
    val POLISHED_BLACKSTONE_SLAB: Item = Items.POLISHED_BLACKSTONE_SLAB
    val POLISHED_BLACKSTONE_STAIRS: Item = Items.POLISHED_BLACKSTONE_STAIRS
    val CHISELED_POLISHED_BLACKSTONE: Item = Items.CHISELED_POLISHED_BLACKSTONE
    val POLISHED_BLACKSTONE_BRICKS: Item = Items.POLISHED_BLACKSTONE_BRICKS
    val POLISHED_BLACKSTONE_BRICK_STAIRS: Item = Items.POLISHED_BLACKSTONE_BRICK_STAIRS
    val CRACKED_POLISHED_BLACKSTONE_BRICKS: Item = Items.CRACKED_POLISHED_BLACKSTONE_BRICKS
    val RESPAWN_ANCHOR: Item = Items.RESPAWN_ANCHOR
    val CANDLE: Item = Items.CANDLE
    val WHITE_CANDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("white_candle"))
    val ORANGE_CANDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("orange_candle"))
    val MAGENTA_CANDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("magenta_candle"))
    val LIGHT_BLUE_CANDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_blue_candle"))
    val YELLOW_CANDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("yellow_candle"))
    val LIME_CANDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("lime_candle"))
    val PINK_CANDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("pink_candle"))
    val GRAY_CANDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("gray_candle"))
    val LIGHT_GRAY_CANDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("light_gray_candle"))
    val CYAN_CANDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("cyan_candle"))
    val PURPLE_CANDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("purple_candle"))
    val BLUE_CANDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("blue_candle"))
    val BROWN_CANDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("brown_candle"))
    val GREEN_CANDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("green_candle"))
    val RED_CANDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("red_candle"))
    val BLACK_CANDLE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("black_candle"))
    val SMALL_AMETHYST_BUD: Item = Items.SMALL_AMETHYST_BUD
    val MEDIUM_AMETHYST_BUD: Item = Items.MEDIUM_AMETHYST_BUD
    val LARGE_AMETHYST_BUD: Item = Items.LARGE_AMETHYST_BUD
    val AMETHYST_CLUSTER: Item = Items.AMETHYST_CLUSTER
    val POINTED_DRIPSTONE: Item = Items.POINTED_DRIPSTONE
    val OCHRE_FROGLIGHT: Item = Items.OCHRE_FROGLIGHT
    val VERDANT_FROGLIGHT: Item = Items.VERDANT_FROGLIGHT
    val PEARLESCENT_FROGLIGHT: Item = Items.PEARLESCENT_FROGLIGHT
    val FROGSPAWN: Item = Items.FROGSPAWN
    val ECHO_SHARD: Item = Items.ECHO_SHARD
    val BRUSH: Item = Items.BRUSH
    val NETHERITE_UPGRADE_SMITHING_TEMPLATE: Item = Items.NETHERITE_UPGRADE_SMITHING_TEMPLATE
    val SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE: Item = Items.SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE
    val DUNE_ARMOR_TRIM_SMITHING_TEMPLATE: Item = Items.DUNE_ARMOR_TRIM_SMITHING_TEMPLATE
    val COAST_ARMOR_TRIM_SMITHING_TEMPLATE: Item = Items.COAST_ARMOR_TRIM_SMITHING_TEMPLATE
    val WILD_ARMOR_TRIM_SMITHING_TEMPLATE: Item = Items.WILD_ARMOR_TRIM_SMITHING_TEMPLATE
    val WARD_ARMOR_TRIM_SMITHING_TEMPLATE: Item = Items.WARD_ARMOR_TRIM_SMITHING_TEMPLATE
    val EYE_ARMOR_TRIM_SMITHING_TEMPLATE: Item = Items.EYE_ARMOR_TRIM_SMITHING_TEMPLATE
    val VEX_ARMOR_TRIM_SMITHING_TEMPLATE: Item = Items.VEX_ARMOR_TRIM_SMITHING_TEMPLATE
    val TIDE_ARMOR_TRIM_SMITHING_TEMPLATE: Item = Items.TIDE_ARMOR_TRIM_SMITHING_TEMPLATE
    val SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE: Item = Items.SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE
    val RIB_ARMOR_TRIM_SMITHING_TEMPLATE: Item = Items.RIB_ARMOR_TRIM_SMITHING_TEMPLATE
    val SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE: Item = Items.SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE
    val WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE: Item = Items.WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE
    val SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE: Item = Items.SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE
    val SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE: Item = Items.SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE
    val RAISER_ARMOR_TRIM_SMITHING_TEMPLATE: Item = Items.RAISER_ARMOR_TRIM_SMITHING_TEMPLATE
    val HOST_ARMOR_TRIM_SMITHING_TEMPLATE: Item = Items.HOST_ARMOR_TRIM_SMITHING_TEMPLATE
    val FLOW_ARMOR_TRIM_SMITHING_TEMPLATE: Item = Items.FLOW_ARMOR_TRIM_SMITHING_TEMPLATE
    val BOLT_ARMOR_TRIM_SMITHING_TEMPLATE: Item = Items.BOLT_ARMOR_TRIM_SMITHING_TEMPLATE
    val ANGLER_POTTERY_SHERD: Item = Items.ANGLER_POTTERY_SHERD
    val ARCHER_POTTERY_SHERD: Item = Items.ARCHER_POTTERY_SHERD
    val ARMS_UP_POTTERY_SHERD: Item = Items.ARMS_UP_POTTERY_SHERD
    val BLADE_POTTERY_SHERD: Item = Items.BLADE_POTTERY_SHERD
    val BREWER_POTTERY_SHERD: Item = Items.BREWER_POTTERY_SHERD
    val BURN_POTTERY_SHERD: Item = Items.BURN_POTTERY_SHERD
    val DANGER_POTTERY_SHERD: Item = Items.DANGER_POTTERY_SHERD
    val EXPLORER_POTTERY_SHERD: Item = Items.EXPLORER_POTTERY_SHERD
    val FLOW_POTTERY_SHERD: Item = Items.FLOW_POTTERY_SHERD
    val FRIEND_POTTERY_SHERD: Item = Items.FRIEND_POTTERY_SHERD
    val GUSTER_POTTERY_SHERD: Item = Items.GUSTER_POTTERY_SHERD
    val HEART_POTTERY_SHERD: Item = Items.HEART_POTTERY_SHERD
    val HEARTBREAK_POTTERY_SHERD: Item = Items.HEARTBREAK_POTTERY_SHERD
    val HOWL_POTTERY_SHERD: Item = Items.HOWL_POTTERY_SHERD
    val MINER_POTTERY_SHERD: Item = Items.MINER_POTTERY_SHERD
    val MOURNER_POTTERY_SHERD: Item = Items.MOURNER_POTTERY_SHERD
    val PLENTY_POTTERY_SHERD: Item = Items.PLENTY_POTTERY_SHERD
    val PRIZE_POTTERY_SHERD: Item = Items.PRIZE_POTTERY_SHERD
    val SCRAPE_POTTERY_SHERD: Item = Items.SCRAPE_POTTERY_SHERD
    val SHEAF_POTTERY_SHERD: Item = Items.SHEAF_POTTERY_SHERD
    val SHELTER_POTTERY_SHERD: Item = Items.SHELTER_POTTERY_SHERD
    val SKULL_POTTERY_SHERD: Item = Items.SKULL_POTTERY_SHERD
    val SNORT_POTTERY_SHERD: Item = Items.SNORT_POTTERY_SHERD
    val COPPER_GRATE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("copper_grate"))
    val EXPOSED_COPPER_GRATE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("exposed_copper_grate"))
    val WEATHERED_COPPER_GRATE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("weathered_copper_grate"))
    val OXIDIZED_COPPER_GRATE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("oxidized_copper_grate"))
    val WAXED_COPPER_GRATE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_copper_grate"))
    val WAXED_EXPOSED_COPPER_GRATE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_exposed_copper_grate"))
    val WAXED_WEATHERED_COPPER_GRATE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_weathered_copper_grate"))
    val WAXED_OXIDIZED_COPPER_GRATE: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_oxidized_copper_grate"))
    val COPPER_BULB: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("copper_bulb"))
    val EXPOSED_COPPER_BULB: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("exposed_copper_bulb"))
    val WEATHERED_COPPER_BULB: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("weathered_copper_bulb"))
    val OXIDIZED_COPPER_BULB: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("oxidized_copper_bulb"))
    val WAXED_COPPER_BULB: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_copper_bulb"))
    val WAXED_EXPOSED_COPPER_BULB: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_exposed_copper_bulb"))
    val WAXED_WEATHERED_COPPER_BULB: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_weathered_copper_bulb"))
    val WAXED_OXIDIZED_COPPER_BULB: Item get() = BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace("waxed_oxidized_copper_bulb"))
    val TRIAL_SPAWNER: Item = Items.TRIAL_SPAWNER
    val TRIAL_KEY: Item = Items.TRIAL_KEY
    val OMINOUS_TRIAL_KEY: Item = Items.OMINOUS_TRIAL_KEY
    val VAULT: Item = Items.VAULT
    val OMINOUS_BOTTLE: Item = Items.OMINOUS_BOTTLE
}
