@file:Suppress("unused")

package com.github.cao.awa.conium.mapping.yarn.reference

import net.minecraft.core.registries.BuiltInRegistries
import net.minecraft.resources.Identifier
import net.minecraft.world.level.block.Block
import net.minecraft.world.level.block.Blocks

object YarnBlocks {
    val STONE: Block = Blocks.STONE
    val GRANITE: Block = Blocks.GRANITE
    val POLISHED_GRANITE: Block = Blocks.POLISHED_GRANITE
    val DIORITE: Block = Blocks.DIORITE
    val POLISHED_DIORITE: Block = Blocks.POLISHED_DIORITE
    val ANDESITE: Block = Blocks.ANDESITE
    val POLISHED_ANDESITE: Block = Blocks.POLISHED_ANDESITE
    val GRASS_BLOCK: Block = Blocks.GRASS_BLOCK
    val DIRT: Block = Blocks.DIRT
    val COARSE_DIRT: Block = Blocks.COARSE_DIRT
    val PODZOL: Block = Blocks.PODZOL
    val COBBLESTONE: Block = Blocks.COBBLESTONE
    val OAK_PLANKS: Block = Blocks.OAK_PLANKS
    val SPRUCE_PLANKS: Block = Blocks.SPRUCE_PLANKS
    val BIRCH_PLANKS: Block = Blocks.BIRCH_PLANKS
    val JUNGLE_PLANKS: Block = Blocks.JUNGLE_PLANKS
    val ACACIA_PLANKS: Block = Blocks.ACACIA_PLANKS
    val CHERRY_PLANKS: Block = Blocks.CHERRY_PLANKS
    val DARK_OAK_PLANKS: Block = Blocks.DARK_OAK_PLANKS
    val PALE_OAK_WOOD: Block = Blocks.PALE_OAK_WOOD
    val PALE_OAK_PLANKS: Block = Blocks.PALE_OAK_PLANKS
    val MANGROVE_PLANKS: Block = Blocks.MANGROVE_PLANKS
    val BAMBOO_PLANKS: Block = Blocks.BAMBOO_PLANKS
    val BAMBOO_MOSAIC: Block = Blocks.BAMBOO_MOSAIC
    val OAK_SAPLING: Block = Blocks.OAK_SAPLING
    val SPRUCE_SAPLING: Block = Blocks.SPRUCE_SAPLING
    val BIRCH_SAPLING: Block = Blocks.BIRCH_SAPLING
    val JUNGLE_SAPLING: Block = Blocks.JUNGLE_SAPLING
    val ACACIA_SAPLING: Block = Blocks.ACACIA_SAPLING
    val CHERRY_SAPLING: Block = Blocks.CHERRY_SAPLING
    val DARK_OAK_SAPLING: Block = Blocks.DARK_OAK_SAPLING
    val PALE_OAK_SAPLING: Block = Blocks.PALE_OAK_SAPLING
    val MANGROVE_PROPAGULE: Block = Blocks.MANGROVE_PROPAGULE
    val BEDROCK: Block = Blocks.BEDROCK
    val WATER: Block = Blocks.WATER
    val LAVA: Block = Blocks.LAVA
    val SAND: Block = Blocks.SAND
    val SUSPICIOUS_SAND: Block = Blocks.SUSPICIOUS_SAND
    val RED_SAND: Block = Blocks.RED_SAND
    val GRAVEL: Block = Blocks.GRAVEL
    val SUSPICIOUS_GRAVEL: Block = Blocks.SUSPICIOUS_GRAVEL
    val GOLD_ORE: Block = Blocks.GOLD_ORE
    val DEEPSLATE_GOLD_ORE: Block = Blocks.DEEPSLATE_GOLD_ORE
    val IRON_ORE: Block = Blocks.IRON_ORE
    val DEEPSLATE_IRON_ORE: Block = Blocks.DEEPSLATE_IRON_ORE
    val COAL_ORE: Block = Blocks.COAL_ORE
    val DEEPSLATE_COAL_ORE: Block = Blocks.DEEPSLATE_COAL_ORE
    val NETHER_GOLD_ORE: Block = Blocks.NETHER_GOLD_ORE
    val OAK_LOG: Block = Blocks.OAK_LOG
    val SPRUCE_LOG: Block = Blocks.SPRUCE_LOG
    val BIRCH_LOG: Block = Blocks.BIRCH_LOG
    val JUNGLE_LOG: Block = Blocks.JUNGLE_LOG
    val ACACIA_LOG: Block = Blocks.ACACIA_LOG
    val CHERRY_LOG: Block = Blocks.CHERRY_LOG
    val DARK_OAK_LOG: Block = Blocks.DARK_OAK_LOG
    val PALE_OAK_LOG: Block = Blocks.PALE_OAK_LOG
    val MANGROVE_LOG: Block = Blocks.MANGROVE_LOG
    val MANGROVE_ROOTS: Block = Blocks.MANGROVE_ROOTS
    val MUDDY_MANGROVE_ROOTS: Block = Blocks.MUDDY_MANGROVE_ROOTS
    val BAMBOO_BLOCK: Block = Blocks.BAMBOO_BLOCK
    val STRIPPED_SPRUCE_LOG: Block = Blocks.STRIPPED_SPRUCE_LOG
    val STRIPPED_BIRCH_LOG: Block = Blocks.STRIPPED_BIRCH_LOG
    val STRIPPED_JUNGLE_LOG: Block = Blocks.STRIPPED_JUNGLE_LOG
    val STRIPPED_ACACIA_LOG: Block = Blocks.STRIPPED_ACACIA_LOG
    val STRIPPED_CHERRY_LOG: Block = Blocks.STRIPPED_CHERRY_LOG
    val STRIPPED_DARK_OAK_LOG: Block = Blocks.STRIPPED_DARK_OAK_LOG
    val STRIPPED_PALE_OAK_LOG: Block = Blocks.STRIPPED_PALE_OAK_LOG
    val STRIPPED_OAK_LOG: Block = Blocks.STRIPPED_OAK_LOG
    val STRIPPED_MANGROVE_LOG: Block = Blocks.STRIPPED_MANGROVE_LOG
    val STRIPPED_BAMBOO_BLOCK: Block = Blocks.STRIPPED_BAMBOO_BLOCK
    val OAK_WOOD: Block = Blocks.OAK_WOOD
    val SPRUCE_WOOD: Block = Blocks.SPRUCE_WOOD
    val BIRCH_WOOD: Block = Blocks.BIRCH_WOOD
    val JUNGLE_WOOD: Block = Blocks.JUNGLE_WOOD
    val ACACIA_WOOD: Block = Blocks.ACACIA_WOOD
    val CHERRY_WOOD: Block = Blocks.CHERRY_WOOD
    val DARK_OAK_WOOD: Block = Blocks.DARK_OAK_WOOD
    val MANGROVE_WOOD: Block = Blocks.MANGROVE_WOOD
    val STRIPPED_OAK_WOOD: Block = Blocks.STRIPPED_OAK_WOOD
    val STRIPPED_SPRUCE_WOOD: Block = Blocks.STRIPPED_SPRUCE_WOOD
    val STRIPPED_BIRCH_WOOD: Block = Blocks.STRIPPED_BIRCH_WOOD
    val STRIPPED_JUNGLE_WOOD: Block = Blocks.STRIPPED_JUNGLE_WOOD
    val STRIPPED_ACACIA_WOOD: Block = Blocks.STRIPPED_ACACIA_WOOD
    val STRIPPED_CHERRY_WOOD: Block = Blocks.STRIPPED_CHERRY_WOOD
    val STRIPPED_DARK_OAK_WOOD: Block = Blocks.STRIPPED_DARK_OAK_WOOD
    val STRIPPED_PALE_OAK_WOOD: Block = Blocks.STRIPPED_PALE_OAK_WOOD
    val STRIPPED_MANGROVE_WOOD: Block = Blocks.STRIPPED_MANGROVE_WOOD
    val OAK_LEAVES: Block = Blocks.OAK_LEAVES
    val SPRUCE_LEAVES: Block = Blocks.SPRUCE_LEAVES
    val BIRCH_LEAVES: Block = Blocks.BIRCH_LEAVES
    val JUNGLE_LEAVES: Block = Blocks.JUNGLE_LEAVES
    val ACACIA_LEAVES: Block = Blocks.ACACIA_LEAVES
    val CHERRY_LEAVES: Block = Blocks.CHERRY_LEAVES
    val DARK_OAK_LEAVES: Block = Blocks.DARK_OAK_LEAVES
    val PALE_OAK_LEAVES: Block = Blocks.PALE_OAK_LEAVES
    val MANGROVE_LEAVES: Block = Blocks.MANGROVE_LEAVES
    val AZALEA_LEAVES: Block = Blocks.AZALEA_LEAVES
    val FLOWERING_AZALEA_LEAVES: Block = Blocks.FLOWERING_AZALEA_LEAVES
    val SPONGE: Block = Blocks.SPONGE
    val WET_SPONGE: Block = Blocks.WET_SPONGE
    val GLASS: Block = Blocks.GLASS
    val LAPIS_ORE: Block = Blocks.LAPIS_ORE
    val DEEPSLATE_LAPIS_ORE: Block = Blocks.DEEPSLATE_LAPIS_ORE
    val LAPIS_BLOCK: Block = Blocks.LAPIS_BLOCK
    val DISPENSER: Block = Blocks.DISPENSER
    val SANDSTONE: Block = Blocks.SANDSTONE
    val CHISELED_SANDSTONE: Block = Blocks.CHISELED_SANDSTONE
    val CUT_SANDSTONE: Block = Blocks.CUT_SANDSTONE
    val NOTE_BLOCK: Block = Blocks.NOTE_BLOCK
    val WHITE_BED: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("white_bed"))
    val ORANGE_BED: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("orange_bed"))
    val MAGENTA_BED: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("magenta_bed"))
    val LIGHT_BLUE_BED: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_blue_bed"))
    val YELLOW_BED: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("yellow_bed"))
    val LIME_BED: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("lime_bed"))
    val PINK_BED: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("pink_bed"))
    val GRAY_BED: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("gray_bed"))
    val LIGHT_GRAY_BED: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_gray_bed"))
    val CYAN_BED: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("cyan_bed"))
    val PURPLE_BED: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("purple_bed"))
    val BLUE_BED: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("blue_bed"))
    val BROWN_BED: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("brown_bed"))
    val GREEN_BED: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("green_bed"))
    val RED_BED: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("red_bed"))
    val BLACK_BED: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("black_bed"))
    val POWERED_RAIL: Block = Blocks.POWERED_RAIL
    val DETECTOR_RAIL: Block = Blocks.DETECTOR_RAIL
    val STICKY_PISTON: Block = Blocks.STICKY_PISTON
    val COBWEB: Block = Blocks.COBWEB
    val SHORT_GRASS: Block = Blocks.SHORT_GRASS
    val FERN: Block = Blocks.FERN
    val DEAD_BUSH: Block = Blocks.DEAD_BUSH
    val BUSH: Block = Blocks.BUSH
    val SHORT_DRY_GRASS: Block = Blocks.SHORT_DRY_GRASS
    val TALL_DRY_GRASS: Block = Blocks.TALL_DRY_GRASS
    val SEAGRASS: Block = Blocks.SEAGRASS
    val TALL_SEAGRASS: Block = Blocks.TALL_SEAGRASS
    val PISTON: Block = Blocks.PISTON
    val PISTON_HEAD: Block = Blocks.PISTON_HEAD
    val WHITE_WOOL: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("white_wool"))
    val ORANGE_WOOL: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("orange_wool"))
    val MAGENTA_WOOL: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("magenta_wool"))
    val LIGHT_BLUE_WOOL: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_blue_wool"))
    val YELLOW_WOOL: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("yellow_wool"))
    val LIME_WOOL: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("lime_wool"))
    val PINK_WOOL: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("pink_wool"))
    val GRAY_WOOL: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("gray_wool"))
    val LIGHT_GRAY_WOOL: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_gray_wool"))
    val CYAN_WOOL: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("cyan_wool"))
    val PURPLE_WOOL: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("purple_wool"))
    val BLUE_WOOL: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("blue_wool"))
    val BROWN_WOOL: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("brown_wool"))
    val GREEN_WOOL: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("green_wool"))
    val RED_WOOL: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("red_wool"))
    val BLACK_WOOL: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("black_wool"))
    val MOVING_PISTON: Block = Blocks.MOVING_PISTON
    val DANDELION: Block = Blocks.DANDELION
    val TORCHFLOWER: Block = Blocks.TORCHFLOWER
    val POPPY: Block = Blocks.POPPY
    val BLUE_ORCHID: Block = Blocks.BLUE_ORCHID
    val ALLIUM: Block = Blocks.ALLIUM
    val AZURE_BLUET: Block = Blocks.AZURE_BLUET
    val RED_TULIP: Block = Blocks.RED_TULIP
    val ORANGE_TULIP: Block = Blocks.ORANGE_TULIP
    val WHITE_TULIP: Block = Blocks.WHITE_TULIP
    val PINK_TULIP: Block = Blocks.PINK_TULIP
    val OXEYE_DAISY: Block = Blocks.OXEYE_DAISY
    val CORNFLOWER: Block = Blocks.CORNFLOWER
    val WITHER_ROSE: Block = Blocks.WITHER_ROSE
    val LILY_OF_THE_VALLEY: Block = Blocks.LILY_OF_THE_VALLEY
    val BROWN_MUSHROOM: Block = Blocks.BROWN_MUSHROOM
    val RED_MUSHROOM: Block = Blocks.RED_MUSHROOM
    val GOLD_BLOCK: Block = Blocks.GOLD_BLOCK
    val IRON_BLOCK: Block = Blocks.IRON_BLOCK
    val BRICKS: Block = Blocks.BRICKS
    val TNT: Block = Blocks.TNT
    val BOOKSHELF: Block = Blocks.BOOKSHELF
    val CHISELED_BOOKSHELF: Block = Blocks.CHISELED_BOOKSHELF
    val MOSSY_COBBLESTONE: Block = Blocks.MOSSY_COBBLESTONE
    val OBSIDIAN: Block = Blocks.OBSIDIAN
    val TORCH: Block = Blocks.TORCH
    val WALL_TORCH: Block = Blocks.WALL_TORCH
    val FIRE: Block = Blocks.FIRE
    val SOUL_FIRE: Block = Blocks.SOUL_FIRE
    val SPAWNER: Block = Blocks.SPAWNER
    val CREAKING_HEART: Block = Blocks.CREAKING_HEART
    val OAK_STAIRS: Block = Blocks.OAK_STAIRS
    val CHEST: Block = Blocks.CHEST
    val REDSTONE_WIRE: Block = Blocks.REDSTONE_WIRE
    val DIAMOND_ORE: Block = Blocks.DIAMOND_ORE
    val DEEPSLATE_DIAMOND_ORE: Block = Blocks.DEEPSLATE_DIAMOND_ORE
    val DIAMOND_BLOCK: Block = Blocks.DIAMOND_BLOCK
    val CRAFTING_TABLE: Block = Blocks.CRAFTING_TABLE
    val WHEAT: Block = Blocks.WHEAT
    val FARMLAND: Block = Blocks.FARMLAND
    val FURNACE: Block = Blocks.FURNACE
    val OAK_SIGN: Block = Blocks.OAK_SIGN
    val SPRUCE_SIGN: Block = Blocks.SPRUCE_SIGN
    val BIRCH_SIGN: Block = Blocks.BIRCH_SIGN
    val ACACIA_SIGN: Block = Blocks.ACACIA_SIGN
    val CHERRY_SIGN: Block = Blocks.CHERRY_SIGN
    val JUNGLE_SIGN: Block = Blocks.JUNGLE_SIGN
    val DARK_OAK_SIGN: Block = Blocks.DARK_OAK_SIGN
    val PALE_OAK_SIGN: Block = Blocks.PALE_OAK_SIGN
    val MANGROVE_SIGN: Block = Blocks.MANGROVE_SIGN
    val BAMBOO_SIGN: Block = Blocks.BAMBOO_SIGN
    val OAK_DOOR: Block = Blocks.OAK_DOOR
    val LADDER: Block = Blocks.LADDER
    val RAIL: Block = Blocks.RAIL
    val COBBLESTONE_STAIRS: Block = Blocks.COBBLESTONE_STAIRS
    val OAK_WALL_SIGN: Block = Blocks.OAK_WALL_SIGN
    val SPRUCE_WALL_SIGN: Block = Blocks.SPRUCE_WALL_SIGN
    val BIRCH_WALL_SIGN: Block = Blocks.BIRCH_WALL_SIGN
    val ACACIA_WALL_SIGN: Block = Blocks.ACACIA_WALL_SIGN
    val CHERRY_WALL_SIGN: Block = Blocks.CHERRY_WALL_SIGN
    val JUNGLE_WALL_SIGN: Block = Blocks.JUNGLE_WALL_SIGN
    val DARK_OAK_WALL_SIGN: Block = Blocks.DARK_OAK_WALL_SIGN
    val PALE_OAK_WALL_SIGN: Block = Blocks.PALE_OAK_WALL_SIGN
    val MANGROVE_WALL_SIGN: Block = Blocks.MANGROVE_WALL_SIGN
    val BAMBOO_WALL_SIGN: Block = Blocks.BAMBOO_WALL_SIGN
    val OAK_HANGING_SIGN: Block = Blocks.OAK_HANGING_SIGN
    val SPRUCE_HANGING_SIGN: Block = Blocks.SPRUCE_HANGING_SIGN
    val BIRCH_HANGING_SIGN: Block = Blocks.BIRCH_HANGING_SIGN
    val ACACIA_HANGING_SIGN: Block = Blocks.ACACIA_HANGING_SIGN
    val CHERRY_HANGING_SIGN: Block = Blocks.CHERRY_HANGING_SIGN
    val JUNGLE_HANGING_SIGN: Block = Blocks.JUNGLE_HANGING_SIGN
    val DARK_OAK_HANGING_SIGN: Block = Blocks.DARK_OAK_HANGING_SIGN
    val PALE_OAK_HANGING_SIGN: Block = Blocks.PALE_OAK_HANGING_SIGN
    val CRIMSON_HANGING_SIGN: Block = Blocks.CRIMSON_HANGING_SIGN
    val WARPED_HANGING_SIGN: Block = Blocks.WARPED_HANGING_SIGN
    val MANGROVE_HANGING_SIGN: Block = Blocks.MANGROVE_HANGING_SIGN
    val BAMBOO_HANGING_SIGN: Block = Blocks.BAMBOO_HANGING_SIGN
    val OAK_WALL_HANGING_SIGN: Block = Blocks.OAK_WALL_HANGING_SIGN
    val SPRUCE_WALL_HANGING_SIGN: Block = Blocks.SPRUCE_WALL_HANGING_SIGN
    val BIRCH_WALL_HANGING_SIGN: Block = Blocks.BIRCH_WALL_HANGING_SIGN
    val ACACIA_WALL_HANGING_SIGN: Block = Blocks.ACACIA_WALL_HANGING_SIGN
    val CHERRY_WALL_HANGING_SIGN: Block = Blocks.CHERRY_WALL_HANGING_SIGN
    val JUNGLE_WALL_HANGING_SIGN: Block = Blocks.JUNGLE_WALL_HANGING_SIGN
    val DARK_OAK_WALL_HANGING_SIGN: Block = Blocks.DARK_OAK_WALL_HANGING_SIGN
    val PALE_OAK_WALL_HANGING_SIGN: Block = Blocks.PALE_OAK_WALL_HANGING_SIGN
    val MANGROVE_WALL_HANGING_SIGN: Block = Blocks.MANGROVE_WALL_HANGING_SIGN
    val CRIMSON_WALL_HANGING_SIGN: Block = Blocks.CRIMSON_WALL_HANGING_SIGN
    val WARPED_WALL_HANGING_SIGN: Block = Blocks.WARPED_WALL_HANGING_SIGN
    val BAMBOO_WALL_HANGING_SIGN: Block = Blocks.BAMBOO_WALL_HANGING_SIGN
    val LEVER: Block = Blocks.LEVER
    val STONE_PRESSURE_PLATE: Block = Blocks.STONE_PRESSURE_PLATE
    val IRON_DOOR: Block = Blocks.IRON_DOOR
    val OAK_PRESSURE_PLATE: Block = Blocks.OAK_PRESSURE_PLATE
    val SPRUCE_PRESSURE_PLATE: Block = Blocks.SPRUCE_PRESSURE_PLATE
    val BIRCH_PRESSURE_PLATE: Block = Blocks.BIRCH_PRESSURE_PLATE
    val JUNGLE_PRESSURE_PLATE: Block = Blocks.JUNGLE_PRESSURE_PLATE
    val ACACIA_PRESSURE_PLATE: Block = Blocks.ACACIA_PRESSURE_PLATE
    val CHERRY_PRESSURE_PLATE: Block = Blocks.CHERRY_PRESSURE_PLATE
    val DARK_OAK_PRESSURE_PLATE: Block = Blocks.DARK_OAK_PRESSURE_PLATE
    val PALE_OAK_PRESSURE_PLATE: Block = Blocks.PALE_OAK_PRESSURE_PLATE
    val MANGROVE_PRESSURE_PLATE: Block = Blocks.MANGROVE_PRESSURE_PLATE
    val BAMBOO_PRESSURE_PLATE: Block = Blocks.BAMBOO_PRESSURE_PLATE
    val REDSTONE_ORE: Block = Blocks.REDSTONE_ORE
    val DEEPSLATE_REDSTONE_ORE: Block = Blocks.DEEPSLATE_REDSTONE_ORE
    val REDSTONE_TORCH: Block = Blocks.REDSTONE_TORCH
    val REDSTONE_WALL_TORCH: Block = Blocks.REDSTONE_WALL_TORCH
    val STONE_BUTTON: Block = Blocks.STONE_BUTTON
    val SNOW: Block = Blocks.SNOW
    val ICE: Block = Blocks.ICE
    val SNOW_BLOCK: Block = Blocks.SNOW_BLOCK
    val CACTUS: Block = Blocks.CACTUS
    val CACTUS_FLOWER: Block = Blocks.CACTUS_FLOWER
    val CLAY: Block = Blocks.CLAY
    val SUGAR_CANE: Block = Blocks.SUGAR_CANE
    val JUKEBOX: Block = Blocks.JUKEBOX
    val OAK_FENCE: Block = Blocks.OAK_FENCE
    val NETHERRACK: Block = Blocks.NETHERRACK
    val SOUL_SAND: Block = Blocks.SOUL_SAND
    val SOUL_SOIL: Block = Blocks.SOUL_SOIL
    val BASALT: Block = Blocks.BASALT
    val POLISHED_BASALT: Block = Blocks.POLISHED_BASALT
    val SOUL_TORCH: Block = Blocks.SOUL_TORCH
    val SOUL_WALL_TORCH: Block = Blocks.SOUL_WALL_TORCH
    val GLOWSTONE: Block = Blocks.GLOWSTONE
    val NETHER_PORTAL: Block = Blocks.NETHER_PORTAL
    val CARVED_PUMPKIN: Block = Blocks.CARVED_PUMPKIN
    val JACK_O_LANTERN: Block = Blocks.JACK_O_LANTERN
    val CAKE: Block = Blocks.CAKE
    val REPEATER: Block = Blocks.REPEATER
    val WHITE_STAINED_GLASS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("white_stained_glass"))
    val ORANGE_STAINED_GLASS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("orange_stained_glass"))
    val MAGENTA_STAINED_GLASS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("magenta_stained_glass"))
    val LIGHT_BLUE_STAINED_GLASS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_blue_stained_glass"))
    val YELLOW_STAINED_GLASS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("yellow_stained_glass"))
    val LIME_STAINED_GLASS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("lime_stained_glass"))
    val PINK_STAINED_GLASS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("pink_stained_glass"))
    val GRAY_STAINED_GLASS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("gray_stained_glass"))
    val LIGHT_GRAY_STAINED_GLASS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_gray_stained_glass"))
    val CYAN_STAINED_GLASS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("cyan_stained_glass"))
    val PURPLE_STAINED_GLASS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("purple_stained_glass"))
    val BLUE_STAINED_GLASS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("blue_stained_glass"))
    val BROWN_STAINED_GLASS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("brown_stained_glass"))
    val GREEN_STAINED_GLASS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("green_stained_glass"))
    val RED_STAINED_GLASS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("red_stained_glass"))
    val BLACK_STAINED_GLASS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("black_stained_glass"))
    val OAK_TRAPDOOR: Block = Blocks.OAK_TRAPDOOR
    val SPRUCE_TRAPDOOR: Block = Blocks.SPRUCE_TRAPDOOR
    val BIRCH_TRAPDOOR: Block = Blocks.BIRCH_TRAPDOOR
    val JUNGLE_TRAPDOOR: Block = Blocks.JUNGLE_TRAPDOOR
    val ACACIA_TRAPDOOR: Block = Blocks.ACACIA_TRAPDOOR
    val CHERRY_TRAPDOOR: Block = Blocks.CHERRY_TRAPDOOR
    val DARK_OAK_TRAPDOOR: Block = Blocks.DARK_OAK_TRAPDOOR
    val PALE_OAK_TRAPDOOR: Block = Blocks.PALE_OAK_TRAPDOOR
    val MANGROVE_TRAPDOOR: Block = Blocks.MANGROVE_TRAPDOOR
    val BAMBOO_TRAPDOOR: Block = Blocks.BAMBOO_TRAPDOOR
    val STONE_BRICKS: Block = Blocks.STONE_BRICKS
    val MOSSY_STONE_BRICKS: Block = Blocks.MOSSY_STONE_BRICKS
    val CRACKED_STONE_BRICKS: Block = Blocks.CRACKED_STONE_BRICKS
    val CHISELED_STONE_BRICKS: Block = Blocks.CHISELED_STONE_BRICKS
    val PACKED_MUD: Block = Blocks.PACKED_MUD
    val MUD_BRICKS: Block = Blocks.MUD_BRICKS
    val INFESTED_STONE: Block = Blocks.INFESTED_STONE
    val INFESTED_COBBLESTONE: Block = Blocks.INFESTED_COBBLESTONE
    val INFESTED_STONE_BRICKS: Block = Blocks.INFESTED_STONE_BRICKS
    val INFESTED_MOSSY_STONE_BRICKS: Block = Blocks.INFESTED_MOSSY_STONE_BRICKS
    val INFESTED_CRACKED_STONE_BRICKS: Block = Blocks.INFESTED_CRACKED_STONE_BRICKS
    val INFESTED_CHISELED_STONE_BRICKS: Block = Blocks.INFESTED_CHISELED_STONE_BRICKS
    val BROWN_MUSHROOM_BLOCK: Block = Blocks.BROWN_MUSHROOM_BLOCK
    val RED_MUSHROOM_BLOCK: Block = Blocks.RED_MUSHROOM_BLOCK
    val MUSHROOM_STEM: Block = Blocks.MUSHROOM_STEM
    val IRON_BARS: Block = Blocks.IRON_BARS
    val IRON_CHAIN: Block = Blocks.IRON_CHAIN
    val GLASS_PANE: Block = Blocks.GLASS_PANE
    val PUMPKIN: Block = Blocks.PUMPKIN
    val MELON: Block = Blocks.MELON
    val ATTACHED_PUMPKIN_STEM: Block = Blocks.ATTACHED_PUMPKIN_STEM
    val ATTACHED_MELON_STEM: Block = Blocks.ATTACHED_MELON_STEM
    val PUMPKIN_STEM: Block = Blocks.PUMPKIN_STEM
    val MELON_STEM: Block = Blocks.MELON_STEM
    val VINE: Block = Blocks.VINE
    val GLOW_LICHEN: Block = Blocks.GLOW_LICHEN
    val RESIN_CLUMP: Block = Blocks.RESIN_CLUMP
    val OAK_FENCE_GATE: Block = Blocks.OAK_FENCE_GATE
    val BRICK_STAIRS: Block = Blocks.BRICK_STAIRS
    val STONE_BRICK_STAIRS: Block = Blocks.STONE_BRICK_STAIRS
    val MUD_BRICK_STAIRS: Block = Blocks.MUD_BRICK_STAIRS
    val MYCELIUM: Block = Blocks.MYCELIUM
    val LILY_PAD: Block = Blocks.LILY_PAD
    val RESIN_BLOCK: Block = Blocks.RESIN_BLOCK
    val RESIN_BRICKS: Block = Blocks.RESIN_BRICKS
    val RESIN_BRICK_STAIRS: Block = Blocks.RESIN_BRICK_STAIRS
    val RESIN_BRICK_SLAB: Block = Blocks.RESIN_BRICK_SLAB
    val RESIN_BRICK_WALL: Block = Blocks.RESIN_BRICK_WALL
    val CHISELED_RESIN_BRICKS: Block = Blocks.CHISELED_RESIN_BRICKS
    val NETHER_BRICKS: Block = Blocks.NETHER_BRICKS
    val NETHER_BRICK_FENCE: Block = Blocks.NETHER_BRICK_FENCE
    val NETHER_BRICK_STAIRS: Block = Blocks.NETHER_BRICK_STAIRS
    val NETHER_WART: Block = Blocks.NETHER_WART
    val ENCHANTING_TABLE: Block = Blocks.ENCHANTING_TABLE
    val BREWING_STAND: Block = Blocks.BREWING_STAND
    val CAULDRON: Block = Blocks.CAULDRON
    val WATER_CAULDRON: Block = Blocks.WATER_CAULDRON
    val LAVA_CAULDRON: Block = Blocks.LAVA_CAULDRON
    val POWDER_SNOW_CAULDRON: Block = Blocks.POWDER_SNOW_CAULDRON
    val END_PORTAL: Block = Blocks.END_PORTAL
    val END_PORTAL_FRAME: Block = Blocks.END_PORTAL_FRAME
    val END_STONE: Block = Blocks.END_STONE
    val DRAGON_EGG: Block = Blocks.DRAGON_EGG
    val REDSTONE_LAMP: Block = Blocks.REDSTONE_LAMP
    val COCOA: Block = Blocks.COCOA
    val SANDSTONE_STAIRS: Block = Blocks.SANDSTONE_STAIRS
    val EMERALD_ORE: Block = Blocks.EMERALD_ORE
    val DEEPSLATE_EMERALD_ORE: Block = Blocks.DEEPSLATE_EMERALD_ORE
    val ENDER_CHEST: Block = Blocks.ENDER_CHEST
    val TRIPWIRE_HOOK: Block = Blocks.TRIPWIRE_HOOK
    val TRIPWIRE: Block = Blocks.TRIPWIRE
    val EMERALD_BLOCK: Block = Blocks.EMERALD_BLOCK
    val SPRUCE_STAIRS: Block = Blocks.SPRUCE_STAIRS
    val BIRCH_STAIRS: Block = Blocks.BIRCH_STAIRS
    val JUNGLE_STAIRS: Block = Blocks.JUNGLE_STAIRS
    val COMMAND_BLOCK: Block = Blocks.COMMAND_BLOCK
    val BEACON: Block = Blocks.BEACON
    val COBBLESTONE_WALL: Block = Blocks.COBBLESTONE_WALL
    val MOSSY_COBBLESTONE_WALL: Block = Blocks.MOSSY_COBBLESTONE_WALL
    val FLOWER_POT: Block = Blocks.FLOWER_POT
    val POTTED_TORCHFLOWER: Block = Blocks.POTTED_TORCHFLOWER
    val POTTED_OAK_SAPLING: Block = Blocks.POTTED_OAK_SAPLING
    val POTTED_SPRUCE_SAPLING: Block = Blocks.POTTED_SPRUCE_SAPLING
    val POTTED_BIRCH_SAPLING: Block = Blocks.POTTED_BIRCH_SAPLING
    val POTTED_JUNGLE_SAPLING: Block = Blocks.POTTED_JUNGLE_SAPLING
    val POTTED_ACACIA_SAPLING: Block = Blocks.POTTED_ACACIA_SAPLING
    val POTTED_CHERRY_SAPLING: Block = Blocks.POTTED_CHERRY_SAPLING
    val POTTED_DARK_OAK_SAPLING: Block = Blocks.POTTED_DARK_OAK_SAPLING
    val POTTED_PALE_OAK_SAPLING: Block = Blocks.POTTED_PALE_OAK_SAPLING
    val POTTED_MANGROVE_PROPAGULE: Block = Blocks.POTTED_MANGROVE_PROPAGULE
    val POTTED_FERN: Block = Blocks.POTTED_FERN
    val POTTED_DANDELION: Block = Blocks.POTTED_DANDELION
    val POTTED_POPPY: Block = Blocks.POTTED_POPPY
    val POTTED_BLUE_ORCHID: Block = Blocks.POTTED_BLUE_ORCHID
    val POTTED_ALLIUM: Block = Blocks.POTTED_ALLIUM
    val POTTED_AZURE_BLUET: Block = Blocks.POTTED_AZURE_BLUET
    val POTTED_RED_TULIP: Block = Blocks.POTTED_RED_TULIP
    val POTTED_ORANGE_TULIP: Block = Blocks.POTTED_ORANGE_TULIP
    val POTTED_WHITE_TULIP: Block = Blocks.POTTED_WHITE_TULIP
    val POTTED_PINK_TULIP: Block = Blocks.POTTED_PINK_TULIP
    val POTTED_OXEYE_DAISY: Block = Blocks.POTTED_OXEYE_DAISY
    val POTTED_CORNFLOWER: Block = Blocks.POTTED_CORNFLOWER
    val POTTED_LILY_OF_THE_VALLEY: Block = Blocks.POTTED_LILY_OF_THE_VALLEY
    val POTTED_WITHER_ROSE: Block = Blocks.POTTED_WITHER_ROSE
    val POTTED_RED_MUSHROOM: Block = Blocks.POTTED_RED_MUSHROOM
    val POTTED_BROWN_MUSHROOM: Block = Blocks.POTTED_BROWN_MUSHROOM
    val POTTED_DEAD_BUSH: Block = Blocks.POTTED_DEAD_BUSH
    val POTTED_CACTUS: Block = Blocks.POTTED_CACTUS
    val CARROTS: Block = Blocks.CARROTS
    val POTATOES: Block = Blocks.POTATOES
    val OAK_BUTTON: Block = Blocks.OAK_BUTTON
    val SPRUCE_BUTTON: Block = Blocks.SPRUCE_BUTTON
    val BIRCH_BUTTON: Block = Blocks.BIRCH_BUTTON
    val JUNGLE_BUTTON: Block = Blocks.JUNGLE_BUTTON
    val ACACIA_BUTTON: Block = Blocks.ACACIA_BUTTON
    val CHERRY_BUTTON: Block = Blocks.CHERRY_BUTTON
    val DARK_OAK_BUTTON: Block = Blocks.DARK_OAK_BUTTON
    val PALE_OAK_BUTTON: Block = Blocks.PALE_OAK_BUTTON
    val MANGROVE_BUTTON: Block = Blocks.MANGROVE_BUTTON
    val BAMBOO_BUTTON: Block = Blocks.BAMBOO_BUTTON
    val SKELETON_SKULL: Block = Blocks.SKELETON_SKULL
    val SKELETON_WALL_SKULL: Block = Blocks.SKELETON_WALL_SKULL
    val WITHER_SKELETON_SKULL: Block = Blocks.WITHER_SKELETON_SKULL
    val WITHER_SKELETON_WALL_SKULL: Block = Blocks.WITHER_SKELETON_WALL_SKULL
    val ZOMBIE_HEAD: Block = Blocks.ZOMBIE_HEAD
    val ZOMBIE_WALL_HEAD: Block = Blocks.ZOMBIE_WALL_HEAD
    val PLAYER_HEAD: Block = Blocks.PLAYER_HEAD
    val PLAYER_WALL_HEAD: Block = Blocks.PLAYER_WALL_HEAD
    val CREEPER_HEAD: Block = Blocks.CREEPER_HEAD
    val CREEPER_WALL_HEAD: Block = Blocks.CREEPER_WALL_HEAD
    val DRAGON_HEAD: Block = Blocks.DRAGON_HEAD
    val DRAGON_WALL_HEAD: Block = Blocks.DRAGON_WALL_HEAD
    val PIGLIN_HEAD: Block = Blocks.PIGLIN_HEAD
    val PIGLIN_WALL_HEAD: Block = Blocks.PIGLIN_WALL_HEAD
    val ANVIL: Block = Blocks.ANVIL
    val CHIPPED_ANVIL: Block = Blocks.CHIPPED_ANVIL
    val DAMAGED_ANVIL: Block = Blocks.DAMAGED_ANVIL
    val TRAPPED_CHEST: Block = Blocks.TRAPPED_CHEST
    val LIGHT_WEIGHTED_PRESSURE_PLATE: Block = Blocks.LIGHT_WEIGHTED_PRESSURE_PLATE
    val HEAVY_WEIGHTED_PRESSURE_PLATE: Block = Blocks.HEAVY_WEIGHTED_PRESSURE_PLATE
    val COMPARATOR: Block = Blocks.COMPARATOR
    val DAYLIGHT_DETECTOR: Block = Blocks.DAYLIGHT_DETECTOR
    val REDSTONE_BLOCK: Block = Blocks.REDSTONE_BLOCK
    val NETHER_QUARTZ_ORE: Block = Blocks.NETHER_QUARTZ_ORE
    val HOPPER: Block = Blocks.HOPPER
    val QUARTZ_BLOCK: Block = Blocks.QUARTZ_BLOCK
    val CHISELED_QUARTZ_BLOCK: Block = Blocks.CHISELED_QUARTZ_BLOCK
    val QUARTZ_PILLAR: Block = Blocks.QUARTZ_PILLAR
    val QUARTZ_STAIRS: Block = Blocks.QUARTZ_STAIRS
    val ACTIVATOR_RAIL: Block = Blocks.ACTIVATOR_RAIL
    val DROPPER: Block = Blocks.DROPPER
    val WHITE_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("white_terracotta"))
    val ORANGE_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("orange_terracotta"))
    val MAGENTA_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("magenta_terracotta"))
    val LIGHT_BLUE_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_blue_terracotta"))
    val YELLOW_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("yellow_terracotta"))
    val LIME_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("lime_terracotta"))
    val PINK_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("pink_terracotta"))
    val GRAY_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("gray_terracotta"))
    val LIGHT_GRAY_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_gray_terracotta"))
    val CYAN_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("cyan_terracotta"))
    val PURPLE_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("purple_terracotta"))
    val BLUE_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("blue_terracotta"))
    val BROWN_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("brown_terracotta"))
    val GREEN_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("green_terracotta"))
    val RED_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("red_terracotta"))
    val BLACK_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("black_terracotta"))
    val WHITE_STAINED_GLASS_PANE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("white_stained_glass_pane"))
    val ORANGE_STAINED_GLASS_PANE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("orange_stained_glass_pane"))
    val MAGENTA_STAINED_GLASS_PANE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("magenta_stained_glass_pane"))
    val LIGHT_BLUE_STAINED_GLASS_PANE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_blue_stained_glass_pane"))
    val YELLOW_STAINED_GLASS_PANE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("yellow_stained_glass_pane"))
    val LIME_STAINED_GLASS_PANE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("lime_stained_glass_pane"))
    val PINK_STAINED_GLASS_PANE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("pink_stained_glass_pane"))
    val GRAY_STAINED_GLASS_PANE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("gray_stained_glass_pane"))
    val LIGHT_GRAY_STAINED_GLASS_PANE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_gray_stained_glass_pane"))
    val CYAN_STAINED_GLASS_PANE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("cyan_stained_glass_pane"))
    val PURPLE_STAINED_GLASS_PANE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("purple_stained_glass_pane"))
    val BLUE_STAINED_GLASS_PANE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("blue_stained_glass_pane"))
    val BROWN_STAINED_GLASS_PANE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("brown_stained_glass_pane"))
    val GREEN_STAINED_GLASS_PANE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("green_stained_glass_pane"))
    val RED_STAINED_GLASS_PANE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("red_stained_glass_pane"))
    val BLACK_STAINED_GLASS_PANE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("black_stained_glass_pane"))
    val ACACIA_STAIRS: Block = Blocks.ACACIA_STAIRS
    val CHERRY_STAIRS: Block = Blocks.CHERRY_STAIRS
    val DARK_OAK_STAIRS: Block = Blocks.DARK_OAK_STAIRS
    val PALE_OAK_STAIRS: Block = Blocks.PALE_OAK_STAIRS
    val MANGROVE_STAIRS: Block = Blocks.MANGROVE_STAIRS
    val BAMBOO_STAIRS: Block = Blocks.BAMBOO_STAIRS
    val BAMBOO_MOSAIC_STAIRS: Block = Blocks.BAMBOO_MOSAIC_STAIRS
    val SLIME_BLOCK: Block = Blocks.SLIME_BLOCK
    val BARRIER: Block = Blocks.BARRIER
    val LIGHT: Block = Blocks.LIGHT
    val IRON_TRAPDOOR: Block = Blocks.IRON_TRAPDOOR
    val PRISMARINE: Block = Blocks.PRISMARINE
    val PRISMARINE_BRICKS: Block = Blocks.PRISMARINE_BRICKS
    val DARK_PRISMARINE: Block = Blocks.DARK_PRISMARINE
    val PRISMARINE_STAIRS: Block = Blocks.PRISMARINE_STAIRS
    val PRISMARINE_BRICK_STAIRS: Block = Blocks.PRISMARINE_BRICK_STAIRS
    val DARK_PRISMARINE_STAIRS: Block = Blocks.DARK_PRISMARINE_STAIRS
    val PRISMARINE_SLAB: Block = Blocks.PRISMARINE_SLAB
    val PRISMARINE_BRICK_SLAB: Block = Blocks.PRISMARINE_BRICK_SLAB
    val DARK_PRISMARINE_SLAB: Block = Blocks.DARK_PRISMARINE_SLAB
    val SEA_LANTERN: Block = Blocks.SEA_LANTERN
    val HAY_BLOCK: Block = Blocks.HAY_BLOCK
    val WHITE_CARPET: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("white_carpet"))
    val ORANGE_CARPET: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("orange_carpet"))
    val MAGENTA_CARPET: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("magenta_carpet"))
    val LIGHT_BLUE_CARPET: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_blue_carpet"))
    val YELLOW_CARPET: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("yellow_carpet"))
    val LIME_CARPET: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("lime_carpet"))
    val PINK_CARPET: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("pink_carpet"))
    val GRAY_CARPET: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("gray_carpet"))
    val LIGHT_GRAY_CARPET: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_gray_carpet"))
    val CYAN_CARPET: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("cyan_carpet"))
    val PURPLE_CARPET: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("purple_carpet"))
    val BLUE_CARPET: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("blue_carpet"))
    val BROWN_CARPET: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("brown_carpet"))
    val GREEN_CARPET: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("green_carpet"))
    val RED_CARPET: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("red_carpet"))
    val BLACK_CARPET: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("black_carpet"))
    val TERRACOTTA: Block = Blocks.TERRACOTTA
    val COAL_BLOCK: Block = Blocks.COAL_BLOCK
    val PACKED_ICE: Block = Blocks.PACKED_ICE
    val SUNFLOWER: Block = Blocks.SUNFLOWER
    val LILAC: Block = Blocks.LILAC
    val ROSE_BUSH: Block = Blocks.ROSE_BUSH
    val PEONY: Block = Blocks.PEONY
    val TALL_GRASS: Block = Blocks.TALL_GRASS
    val LARGE_FERN: Block = Blocks.LARGE_FERN
    val WHITE_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("white_banner"))
    val ORANGE_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("orange_banner"))
    val MAGENTA_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("magenta_banner"))
    val LIGHT_BLUE_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_blue_banner"))
    val YELLOW_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("yellow_banner"))
    val LIME_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("lime_banner"))
    val PINK_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("pink_banner"))
    val GRAY_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("gray_banner"))
    val LIGHT_GRAY_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_gray_banner"))
    val CYAN_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("cyan_banner"))
    val PURPLE_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("purple_banner"))
    val BLUE_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("blue_banner"))
    val BROWN_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("brown_banner"))
    val GREEN_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("green_banner"))
    val RED_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("red_banner"))
    val BLACK_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("black_banner"))
    val WHITE_WALL_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("white_wall_banner"))
    val ORANGE_WALL_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("orange_wall_banner"))
    val MAGENTA_WALL_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("magenta_wall_banner"))
    val LIGHT_BLUE_WALL_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_blue_wall_banner"))
    val YELLOW_WALL_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("yellow_wall_banner"))
    val LIME_WALL_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("lime_wall_banner"))
    val PINK_WALL_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("pink_wall_banner"))
    val GRAY_WALL_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("gray_wall_banner"))
    val LIGHT_GRAY_WALL_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_gray_wall_banner"))
    val CYAN_WALL_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("cyan_wall_banner"))
    val PURPLE_WALL_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("purple_wall_banner"))
    val BLUE_WALL_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("blue_wall_banner"))
    val BROWN_WALL_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("brown_wall_banner"))
    val GREEN_WALL_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("green_wall_banner"))
    val RED_WALL_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("red_wall_banner"))
    val BLACK_WALL_BANNER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("black_wall_banner"))
    val RED_SANDSTONE: Block = Blocks.RED_SANDSTONE
    val CHISELED_RED_SANDSTONE: Block = Blocks.CHISELED_RED_SANDSTONE
    val CUT_RED_SANDSTONE: Block = Blocks.CUT_RED_SANDSTONE
    val RED_SANDSTONE_STAIRS: Block = Blocks.RED_SANDSTONE_STAIRS
    val OAK_SLAB: Block = Blocks.OAK_SLAB
    val SPRUCE_SLAB: Block = Blocks.SPRUCE_SLAB
    val BIRCH_SLAB: Block = Blocks.BIRCH_SLAB
    val JUNGLE_SLAB: Block = Blocks.JUNGLE_SLAB
    val ACACIA_SLAB: Block = Blocks.ACACIA_SLAB
    val CHERRY_SLAB: Block = Blocks.CHERRY_SLAB
    val DARK_OAK_SLAB: Block = Blocks.DARK_OAK_SLAB
    val PALE_OAK_SLAB: Block = Blocks.PALE_OAK_SLAB
    val MANGROVE_SLAB: Block = Blocks.MANGROVE_SLAB
    val BAMBOO_SLAB: Block = Blocks.BAMBOO_SLAB
    val BAMBOO_MOSAIC_SLAB: Block = Blocks.BAMBOO_MOSAIC_SLAB
    val STONE_SLAB: Block = Blocks.STONE_SLAB
    val SMOOTH_STONE_SLAB: Block = Blocks.SMOOTH_STONE_SLAB
    val SANDSTONE_SLAB: Block = Blocks.SANDSTONE_SLAB
    val CUT_SANDSTONE_SLAB: Block = Blocks.CUT_SANDSTONE_SLAB
    val PETRIFIED_OAK_SLAB: Block = Blocks.PETRIFIED_OAK_SLAB
    val COBBLESTONE_SLAB: Block = Blocks.COBBLESTONE_SLAB
    val BRICK_SLAB: Block = Blocks.BRICK_SLAB
    val STONE_BRICK_SLAB: Block = Blocks.STONE_BRICK_SLAB
    val MUD_BRICK_SLAB: Block = Blocks.MUD_BRICK_SLAB
    val NETHER_BRICK_SLAB: Block = Blocks.NETHER_BRICK_SLAB
    val QUARTZ_SLAB: Block = Blocks.QUARTZ_SLAB
    val RED_SANDSTONE_SLAB: Block = Blocks.RED_SANDSTONE_SLAB
    val CUT_RED_SANDSTONE_SLAB: Block = Blocks.CUT_RED_SANDSTONE_SLAB
    val PURPUR_SLAB: Block = Blocks.PURPUR_SLAB
    val SMOOTH_STONE: Block = Blocks.SMOOTH_STONE
    val SMOOTH_SANDSTONE: Block = Blocks.SMOOTH_SANDSTONE
    val SMOOTH_QUARTZ: Block = Blocks.SMOOTH_QUARTZ
    val SMOOTH_RED_SANDSTONE: Block = Blocks.SMOOTH_RED_SANDSTONE
    val SPRUCE_FENCE_GATE: Block = Blocks.SPRUCE_FENCE_GATE
    val BIRCH_FENCE_GATE: Block = Blocks.BIRCH_FENCE_GATE
    val JUNGLE_FENCE_GATE: Block = Blocks.JUNGLE_FENCE_GATE
    val ACACIA_FENCE_GATE: Block = Blocks.ACACIA_FENCE_GATE
    val CHERRY_FENCE_GATE: Block = Blocks.CHERRY_FENCE_GATE
    val DARK_OAK_FENCE_GATE: Block = Blocks.DARK_OAK_FENCE_GATE
    val PALE_OAK_FENCE_GATE: Block = Blocks.PALE_OAK_FENCE_GATE
    val MANGROVE_FENCE_GATE: Block = Blocks.MANGROVE_FENCE_GATE
    val BAMBOO_FENCE_GATE: Block = Blocks.BAMBOO_FENCE_GATE
    val SPRUCE_FENCE: Block = Blocks.SPRUCE_FENCE
    val BIRCH_FENCE: Block = Blocks.BIRCH_FENCE
    val JUNGLE_FENCE: Block = Blocks.JUNGLE_FENCE
    val ACACIA_FENCE: Block = Blocks.ACACIA_FENCE
    val CHERRY_FENCE: Block = Blocks.CHERRY_FENCE
    val DARK_OAK_FENCE: Block = Blocks.DARK_OAK_FENCE
    val PALE_OAK_FENCE: Block = Blocks.PALE_OAK_FENCE
    val MANGROVE_FENCE: Block = Blocks.MANGROVE_FENCE
    val BAMBOO_FENCE: Block = Blocks.BAMBOO_FENCE
    val SPRUCE_DOOR: Block = Blocks.SPRUCE_DOOR
    val BIRCH_DOOR: Block = Blocks.BIRCH_DOOR
    val JUNGLE_DOOR: Block = Blocks.JUNGLE_DOOR
    val ACACIA_DOOR: Block = Blocks.ACACIA_DOOR
    val CHERRY_DOOR: Block = Blocks.CHERRY_DOOR
    val DARK_OAK_DOOR: Block = Blocks.DARK_OAK_DOOR
    val PALE_OAK_DOOR: Block = Blocks.PALE_OAK_DOOR
    val MANGROVE_DOOR: Block = Blocks.MANGROVE_DOOR
    val BAMBOO_DOOR: Block = Blocks.BAMBOO_DOOR
    val END_ROD: Block = Blocks.END_ROD
    val CHORUS_PLANT: Block = Blocks.CHORUS_PLANT
    val CHORUS_FLOWER: Block = Blocks.CHORUS_FLOWER
    val PURPUR_BLOCK: Block = Blocks.PURPUR_BLOCK
    val PURPUR_PILLAR: Block = Blocks.PURPUR_PILLAR
    val PURPUR_STAIRS: Block = Blocks.PURPUR_STAIRS
    val END_STONE_BRICKS: Block = Blocks.END_STONE_BRICKS
    val TORCHFLOWER_CROP: Block = Blocks.TORCHFLOWER_CROP
    val PITCHER_CROP: Block = Blocks.PITCHER_CROP
    val PITCHER_PLANT: Block = Blocks.PITCHER_PLANT
    val BEETROOTS: Block = Blocks.BEETROOTS
    val DIRT_PATH: Block = Blocks.DIRT_PATH
    val END_GATEWAY: Block = Blocks.END_GATEWAY
    val REPEATING_COMMAND_BLOCK: Block = Blocks.REPEATING_COMMAND_BLOCK
    val CHAIN_COMMAND_BLOCK: Block = Blocks.CHAIN_COMMAND_BLOCK
    val FROSTED_ICE: Block = Blocks.FROSTED_ICE
    val MAGMA_BLOCK: Block = Blocks.MAGMA_BLOCK
    val NETHER_WART_BLOCK: Block = Blocks.NETHER_WART_BLOCK
    val RED_NETHER_BRICKS: Block = Blocks.RED_NETHER_BRICKS
    val BONE_BLOCK: Block = Blocks.BONE_BLOCK
    val STRUCTURE_VOID: Block = Blocks.STRUCTURE_VOID
    val OBSERVER: Block = Blocks.OBSERVER
    val SHULKER_BOX: Block = Blocks.SHULKER_BOX
    val WHITE_SHULKER_BOX: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("white_shulker_box"))
    val ORANGE_SHULKER_BOX: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("orange_shulker_box"))
    val MAGENTA_SHULKER_BOX: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("magenta_shulker_box"))
    val LIGHT_BLUE_SHULKER_BOX: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_blue_shulker_box"))
    val YELLOW_SHULKER_BOX: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("yellow_shulker_box"))
    val LIME_SHULKER_BOX: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("lime_shulker_box"))
    val PINK_SHULKER_BOX: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("pink_shulker_box"))
    val GRAY_SHULKER_BOX: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("gray_shulker_box"))
    val LIGHT_GRAY_SHULKER_BOX: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_gray_shulker_box"))
    val CYAN_SHULKER_BOX: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("cyan_shulker_box"))
    val PURPLE_SHULKER_BOX: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("purple_shulker_box"))
    val BLUE_SHULKER_BOX: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("blue_shulker_box"))
    val BROWN_SHULKER_BOX: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("brown_shulker_box"))
    val GREEN_SHULKER_BOX: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("green_shulker_box"))
    val RED_SHULKER_BOX: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("red_shulker_box"))
    val BLACK_SHULKER_BOX: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("black_shulker_box"))
    val WHITE_GLAZED_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("white_glazed_terracotta"))
    val ORANGE_GLAZED_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("orange_glazed_terracotta"))
    val MAGENTA_GLAZED_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("magenta_glazed_terracotta"))
    val LIGHT_BLUE_GLAZED_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_blue_glazed_terracotta"))
    val YELLOW_GLAZED_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("yellow_glazed_terracotta"))
    val LIME_GLAZED_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("lime_glazed_terracotta"))
    val PINK_GLAZED_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("pink_glazed_terracotta"))
    val GRAY_GLAZED_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("gray_glazed_terracotta"))
    val LIGHT_GRAY_GLAZED_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_gray_glazed_terracotta"))
    val CYAN_GLAZED_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("cyan_glazed_terracotta"))
    val PURPLE_GLAZED_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("purple_glazed_terracotta"))
    val BLUE_GLAZED_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("blue_glazed_terracotta"))
    val BROWN_GLAZED_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("brown_glazed_terracotta"))
    val GREEN_GLAZED_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("green_glazed_terracotta"))
    val RED_GLAZED_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("red_glazed_terracotta"))
    val BLACK_GLAZED_TERRACOTTA: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("black_glazed_terracotta"))
    val WHITE_CONCRETE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("white_concrete"))
    val ORANGE_CONCRETE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("orange_concrete"))
    val MAGENTA_CONCRETE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("magenta_concrete"))
    val LIGHT_BLUE_CONCRETE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_blue_concrete"))
    val YELLOW_CONCRETE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("yellow_concrete"))
    val LIME_CONCRETE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("lime_concrete"))
    val PINK_CONCRETE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("pink_concrete"))
    val GRAY_CONCRETE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("gray_concrete"))
    val LIGHT_GRAY_CONCRETE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_gray_concrete"))
    val CYAN_CONCRETE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("cyan_concrete"))
    val PURPLE_CONCRETE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("purple_concrete"))
    val BLUE_CONCRETE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("blue_concrete"))
    val BROWN_CONCRETE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("brown_concrete"))
    val GREEN_CONCRETE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("green_concrete"))
    val RED_CONCRETE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("red_concrete"))
    val BLACK_CONCRETE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("black_concrete"))
    val WHITE_CONCRETE_POWDER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("white_concrete_powder"))
    val ORANGE_CONCRETE_POWDER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("orange_concrete_powder"))
    val MAGENTA_CONCRETE_POWDER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("magenta_concrete_powder"))
    val LIGHT_BLUE_CONCRETE_POWDER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_blue_concrete_powder"))
    val YELLOW_CONCRETE_POWDER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("yellow_concrete_powder"))
    val LIME_CONCRETE_POWDER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("lime_concrete_powder"))
    val PINK_CONCRETE_POWDER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("pink_concrete_powder"))
    val GRAY_CONCRETE_POWDER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("gray_concrete_powder"))
    val LIGHT_GRAY_CONCRETE_POWDER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_gray_concrete_powder"))
    val CYAN_CONCRETE_POWDER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("cyan_concrete_powder"))
    val PURPLE_CONCRETE_POWDER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("purple_concrete_powder"))
    val BLUE_CONCRETE_POWDER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("blue_concrete_powder"))
    val BROWN_CONCRETE_POWDER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("brown_concrete_powder"))
    val GREEN_CONCRETE_POWDER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("green_concrete_powder"))
    val RED_CONCRETE_POWDER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("red_concrete_powder"))
    val BLACK_CONCRETE_POWDER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("black_concrete_powder"))
    val KELP: Block = Blocks.KELP
    val KELP_PLANT: Block = Blocks.KELP_PLANT
    val DRIED_KELP_BLOCK: Block = Blocks.DRIED_KELP_BLOCK
    val TURTLE_EGG: Block = Blocks.TURTLE_EGG
    val SNIFFER_EGG: Block = Blocks.SNIFFER_EGG
    val DRIED_GHAST: Block = Blocks.DRIED_GHAST
    val DEAD_TUBE_CORAL_BLOCK: Block = Blocks.DEAD_TUBE_CORAL_BLOCK
    val DEAD_BRAIN_CORAL_BLOCK: Block = Blocks.DEAD_BRAIN_CORAL_BLOCK
    val DEAD_BUBBLE_CORAL_BLOCK: Block = Blocks.DEAD_BUBBLE_CORAL_BLOCK
    val DEAD_FIRE_CORAL_BLOCK: Block = Blocks.DEAD_FIRE_CORAL_BLOCK
    val DEAD_HORN_CORAL_BLOCK: Block = Blocks.DEAD_HORN_CORAL_BLOCK
    val TUBE_CORAL_BLOCK: Block = Blocks.TUBE_CORAL_BLOCK
    val BRAIN_CORAL_BLOCK: Block = Blocks.BRAIN_CORAL_BLOCK
    val BUBBLE_CORAL_BLOCK: Block = Blocks.BUBBLE_CORAL_BLOCK
    val FIRE_CORAL_BLOCK: Block = Blocks.FIRE_CORAL_BLOCK
    val HORN_CORAL_BLOCK: Block = Blocks.HORN_CORAL_BLOCK
    val DEAD_TUBE_CORAL: Block = Blocks.DEAD_TUBE_CORAL
    val DEAD_BRAIN_CORAL: Block = Blocks.DEAD_BRAIN_CORAL
    val DEAD_BUBBLE_CORAL: Block = Blocks.DEAD_BUBBLE_CORAL
    val DEAD_FIRE_CORAL: Block = Blocks.DEAD_FIRE_CORAL
    val DEAD_HORN_CORAL: Block = Blocks.DEAD_HORN_CORAL
    val TUBE_CORAL: Block = Blocks.TUBE_CORAL
    val BRAIN_CORAL: Block = Blocks.BRAIN_CORAL
    val BUBBLE_CORAL: Block = Blocks.BUBBLE_CORAL
    val FIRE_CORAL: Block = Blocks.FIRE_CORAL
    val HORN_CORAL: Block = Blocks.HORN_CORAL
    val DEAD_TUBE_CORAL_FAN: Block = Blocks.DEAD_TUBE_CORAL_FAN
    val DEAD_BRAIN_CORAL_FAN: Block = Blocks.DEAD_BRAIN_CORAL_FAN
    val DEAD_BUBBLE_CORAL_FAN: Block = Blocks.DEAD_BUBBLE_CORAL_FAN
    val DEAD_FIRE_CORAL_FAN: Block = Blocks.DEAD_FIRE_CORAL_FAN
    val DEAD_HORN_CORAL_FAN: Block = Blocks.DEAD_HORN_CORAL_FAN
    val TUBE_CORAL_FAN: Block = Blocks.TUBE_CORAL_FAN
    val BRAIN_CORAL_FAN: Block = Blocks.BRAIN_CORAL_FAN
    val BUBBLE_CORAL_FAN: Block = Blocks.BUBBLE_CORAL_FAN
    val FIRE_CORAL_FAN: Block = Blocks.FIRE_CORAL_FAN
    val HORN_CORAL_FAN: Block = Blocks.HORN_CORAL_FAN
    val DEAD_TUBE_CORAL_WALL_FAN: Block = Blocks.DEAD_TUBE_CORAL_WALL_FAN
    val DEAD_BRAIN_CORAL_WALL_FAN: Block = Blocks.DEAD_BRAIN_CORAL_WALL_FAN
    val DEAD_BUBBLE_CORAL_WALL_FAN: Block = Blocks.DEAD_BUBBLE_CORAL_WALL_FAN
    val DEAD_FIRE_CORAL_WALL_FAN: Block = Blocks.DEAD_FIRE_CORAL_WALL_FAN
    val DEAD_HORN_CORAL_WALL_FAN: Block = Blocks.DEAD_HORN_CORAL_WALL_FAN
    val TUBE_CORAL_WALL_FAN: Block = Blocks.TUBE_CORAL_WALL_FAN
    val BRAIN_CORAL_WALL_FAN: Block = Blocks.BRAIN_CORAL_WALL_FAN
    val BUBBLE_CORAL_WALL_FAN: Block = Blocks.BUBBLE_CORAL_WALL_FAN
    val FIRE_CORAL_WALL_FAN: Block = Blocks.FIRE_CORAL_WALL_FAN
    val HORN_CORAL_WALL_FAN: Block = Blocks.HORN_CORAL_WALL_FAN
    val SEA_PICKLE: Block = Blocks.SEA_PICKLE
    val BLUE_ICE: Block = Blocks.BLUE_ICE
    val CONDUIT: Block = Blocks.CONDUIT
    val BAMBOO_SAPLING: Block = Blocks.BAMBOO_SAPLING
    val BAMBOO: Block = Blocks.BAMBOO
    val POTTED_BAMBOO: Block = Blocks.POTTED_BAMBOO
    val VOID_AIR: Block = Blocks.VOID_AIR
    val CAVE_AIR: Block = Blocks.CAVE_AIR
    val BUBBLE_COLUMN: Block = Blocks.BUBBLE_COLUMN
    val POLISHED_GRANITE_STAIRS: Block = Blocks.POLISHED_GRANITE_STAIRS
    val SMOOTH_RED_SANDSTONE_STAIRS: Block = Blocks.SMOOTH_RED_SANDSTONE_STAIRS
    val MOSSY_STONE_BRICK_STAIRS: Block = Blocks.MOSSY_STONE_BRICK_STAIRS
    val POLISHED_DIORITE_STAIRS: Block = Blocks.POLISHED_DIORITE_STAIRS
    val MOSSY_COBBLESTONE_STAIRS: Block = Blocks.MOSSY_COBBLESTONE_STAIRS
    val END_STONE_BRICK_STAIRS: Block = Blocks.END_STONE_BRICK_STAIRS
    val STONE_STAIRS: Block = Blocks.STONE_STAIRS
    val SMOOTH_SANDSTONE_STAIRS: Block = Blocks.SMOOTH_SANDSTONE_STAIRS
    val SMOOTH_QUARTZ_STAIRS: Block = Blocks.SMOOTH_QUARTZ_STAIRS
    val GRANITE_STAIRS: Block = Blocks.GRANITE_STAIRS
    val ANDESITE_STAIRS: Block = Blocks.ANDESITE_STAIRS
    val RED_NETHER_BRICK_STAIRS: Block = Blocks.RED_NETHER_BRICK_STAIRS
    val POLISHED_ANDESITE_STAIRS: Block = Blocks.POLISHED_ANDESITE_STAIRS
    val DIORITE_STAIRS: Block = Blocks.DIORITE_STAIRS
    val POLISHED_GRANITE_SLAB: Block = Blocks.POLISHED_GRANITE_SLAB
    val SMOOTH_RED_SANDSTONE_SLAB: Block = Blocks.SMOOTH_RED_SANDSTONE_SLAB
    val MOSSY_STONE_BRICK_SLAB: Block = Blocks.MOSSY_STONE_BRICK_SLAB
    val POLISHED_DIORITE_SLAB: Block = Blocks.POLISHED_DIORITE_SLAB
    val MOSSY_COBBLESTONE_SLAB: Block = Blocks.MOSSY_COBBLESTONE_SLAB
    val END_STONE_BRICK_SLAB: Block = Blocks.END_STONE_BRICK_SLAB
    val SMOOTH_SANDSTONE_SLAB: Block = Blocks.SMOOTH_SANDSTONE_SLAB
    val SMOOTH_QUARTZ_SLAB: Block = Blocks.SMOOTH_QUARTZ_SLAB
    val GRANITE_SLAB: Block = Blocks.GRANITE_SLAB
    val ANDESITE_SLAB: Block = Blocks.ANDESITE_SLAB
    val RED_NETHER_BRICK_SLAB: Block = Blocks.RED_NETHER_BRICK_SLAB
    val POLISHED_ANDESITE_SLAB: Block = Blocks.POLISHED_ANDESITE_SLAB
    val DIORITE_SLAB: Block = Blocks.DIORITE_SLAB
    val BRICK_WALL: Block = Blocks.BRICK_WALL
    val PRISMARINE_WALL: Block = Blocks.PRISMARINE_WALL
    val RED_SANDSTONE_WALL: Block = Blocks.RED_SANDSTONE_WALL
    val MOSSY_STONE_BRICK_WALL: Block = Blocks.MOSSY_STONE_BRICK_WALL
    val GRANITE_WALL: Block = Blocks.GRANITE_WALL
    val STONE_BRICK_WALL: Block = Blocks.STONE_BRICK_WALL
    val MUD_BRICK_WALL: Block = Blocks.MUD_BRICK_WALL
    val NETHER_BRICK_WALL: Block = Blocks.NETHER_BRICK_WALL
    val ANDESITE_WALL: Block = Blocks.ANDESITE_WALL
    val RED_NETHER_BRICK_WALL: Block = Blocks.RED_NETHER_BRICK_WALL
    val SANDSTONE_WALL: Block = Blocks.SANDSTONE_WALL
    val END_STONE_BRICK_WALL: Block = Blocks.END_STONE_BRICK_WALL
    val DIORITE_WALL: Block = Blocks.DIORITE_WALL
    val SCAFFOLDING: Block = Blocks.SCAFFOLDING
    val LOOM: Block = Blocks.LOOM
    val BARREL: Block = Blocks.BARREL
    val SMOKER: Block = Blocks.SMOKER
    val BLAST_FURNACE: Block = Blocks.BLAST_FURNACE
    val CARTOGRAPHY_TABLE: Block = Blocks.CARTOGRAPHY_TABLE
    val FLETCHING_TABLE: Block = Blocks.FLETCHING_TABLE
    val GRINDSTONE: Block = Blocks.GRINDSTONE
    val LECTERN: Block = Blocks.LECTERN
    val SMITHING_TABLE: Block = Blocks.SMITHING_TABLE
    val STONECUTTER: Block = Blocks.STONECUTTER
    val BELL: Block = Blocks.BELL
    val LANTERN: Block = Blocks.LANTERN
    val SOUL_LANTERN: Block = Blocks.SOUL_LANTERN
    val CAMPFIRE: Block = Blocks.CAMPFIRE
    val SOUL_CAMPFIRE: Block = Blocks.SOUL_CAMPFIRE
    val SWEET_BERRY_BUSH: Block = Blocks.SWEET_BERRY_BUSH
    val WARPED_STEM: Block = Blocks.WARPED_STEM
    val STRIPPED_WARPED_STEM: Block = Blocks.STRIPPED_WARPED_STEM
    val WARPED_HYPHAE: Block = Blocks.WARPED_HYPHAE
    val STRIPPED_WARPED_HYPHAE: Block = Blocks.STRIPPED_WARPED_HYPHAE
    val WARPED_NYLIUM: Block = Blocks.WARPED_NYLIUM
    val WARPED_FUNGUS: Block = Blocks.WARPED_FUNGUS
    val WARPED_WART_BLOCK: Block = Blocks.WARPED_WART_BLOCK
    val WARPED_ROOTS: Block = Blocks.WARPED_ROOTS
    val NETHER_SPROUTS: Block = Blocks.NETHER_SPROUTS
    val CRIMSON_STEM: Block = Blocks.CRIMSON_STEM
    val STRIPPED_CRIMSON_STEM: Block = Blocks.STRIPPED_CRIMSON_STEM
    val CRIMSON_HYPHAE: Block = Blocks.CRIMSON_HYPHAE
    val STRIPPED_CRIMSON_HYPHAE: Block = Blocks.STRIPPED_CRIMSON_HYPHAE
    val CRIMSON_NYLIUM: Block = Blocks.CRIMSON_NYLIUM
    val CRIMSON_FUNGUS: Block = Blocks.CRIMSON_FUNGUS
    val SHROOMLIGHT: Block = Blocks.SHROOMLIGHT
    val WEEPING_VINES: Block = Blocks.WEEPING_VINES
    val WEEPING_VINES_PLANT: Block = Blocks.WEEPING_VINES_PLANT
    val TWISTING_VINES: Block = Blocks.TWISTING_VINES
    val TWISTING_VINES_PLANT: Block = Blocks.TWISTING_VINES_PLANT
    val CRIMSON_ROOTS: Block = Blocks.CRIMSON_ROOTS
    val CRIMSON_PLANKS: Block = Blocks.CRIMSON_PLANKS
    val WARPED_PLANKS: Block = Blocks.WARPED_PLANKS
    val CRIMSON_SLAB: Block = Blocks.CRIMSON_SLAB
    val WARPED_SLAB: Block = Blocks.WARPED_SLAB
    val CRIMSON_PRESSURE_PLATE: Block = Blocks.CRIMSON_PRESSURE_PLATE
    val WARPED_PRESSURE_PLATE: Block = Blocks.WARPED_PRESSURE_PLATE
    val CRIMSON_FENCE: Block = Blocks.CRIMSON_FENCE
    val WARPED_FENCE: Block = Blocks.WARPED_FENCE
    val CRIMSON_TRAPDOOR: Block = Blocks.CRIMSON_TRAPDOOR
    val WARPED_TRAPDOOR: Block = Blocks.WARPED_TRAPDOOR
    val CRIMSON_FENCE_GATE: Block = Blocks.CRIMSON_FENCE_GATE
    val WARPED_FENCE_GATE: Block = Blocks.WARPED_FENCE_GATE
    val CRIMSON_STAIRS: Block = Blocks.CRIMSON_STAIRS
    val WARPED_STAIRS: Block = Blocks.WARPED_STAIRS
    val CRIMSON_BUTTON: Block = Blocks.CRIMSON_BUTTON
    val WARPED_BUTTON: Block = Blocks.WARPED_BUTTON
    val CRIMSON_DOOR: Block = Blocks.CRIMSON_DOOR
    val WARPED_DOOR: Block = Blocks.WARPED_DOOR
    val CRIMSON_SIGN: Block = Blocks.CRIMSON_SIGN
    val WARPED_SIGN: Block = Blocks.WARPED_SIGN
    val CRIMSON_WALL_SIGN: Block = Blocks.CRIMSON_WALL_SIGN
    val WARPED_WALL_SIGN: Block = Blocks.WARPED_WALL_SIGN
    val STRUCTURE_BLOCK: Block = Blocks.STRUCTURE_BLOCK
    val JIGSAW: Block = Blocks.JIGSAW
    val TEST_BLOCK: Block = Blocks.TEST_BLOCK
    val TEST_INSTANCE_BLOCK: Block = Blocks.TEST_INSTANCE_BLOCK
    val COMPOSTER: Block = Blocks.COMPOSTER
    val TARGET: Block = Blocks.TARGET
    val BEE_NEST: Block = Blocks.BEE_NEST
    val BEEHIVE: Block = Blocks.BEEHIVE
    val HONEY_BLOCK: Block = Blocks.HONEY_BLOCK
    val HONEYCOMB_BLOCK: Block = Blocks.HONEYCOMB_BLOCK
    val NETHERITE_BLOCK: Block = Blocks.NETHERITE_BLOCK
    val ANCIENT_DEBRIS: Block = Blocks.ANCIENT_DEBRIS
    val CRYING_OBSIDIAN: Block = Blocks.CRYING_OBSIDIAN
    val RESPAWN_ANCHOR: Block = Blocks.RESPAWN_ANCHOR
    val POTTED_CRIMSON_FUNGUS: Block = Blocks.POTTED_CRIMSON_FUNGUS
    val POTTED_WARPED_FUNGUS: Block = Blocks.POTTED_WARPED_FUNGUS
    val POTTED_CRIMSON_ROOTS: Block = Blocks.POTTED_CRIMSON_ROOTS
    val POTTED_WARPED_ROOTS: Block = Blocks.POTTED_WARPED_ROOTS
    val LODESTONE: Block = Blocks.LODESTONE
    val BLACKSTONE: Block = Blocks.BLACKSTONE
    val BLACKSTONE_STAIRS: Block = Blocks.BLACKSTONE_STAIRS
    val BLACKSTONE_WALL: Block = Blocks.BLACKSTONE_WALL
    val BLACKSTONE_SLAB: Block = Blocks.BLACKSTONE_SLAB
    val POLISHED_BLACKSTONE: Block = Blocks.POLISHED_BLACKSTONE
    val POLISHED_BLACKSTONE_BRICKS: Block = Blocks.POLISHED_BLACKSTONE_BRICKS
    val CRACKED_POLISHED_BLACKSTONE_BRICKS: Block = Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS
    val CHISELED_POLISHED_BLACKSTONE: Block = Blocks.CHISELED_POLISHED_BLACKSTONE
    val POLISHED_BLACKSTONE_BRICK_SLAB: Block = Blocks.POLISHED_BLACKSTONE_BRICK_SLAB
    val POLISHED_BLACKSTONE_BRICK_STAIRS: Block = Blocks.POLISHED_BLACKSTONE_BRICK_STAIRS
    val POLISHED_BLACKSTONE_BRICK_WALL: Block = Blocks.POLISHED_BLACKSTONE_BRICK_WALL
    val GILDED_BLACKSTONE: Block = Blocks.GILDED_BLACKSTONE
    val POLISHED_BLACKSTONE_STAIRS: Block = Blocks.POLISHED_BLACKSTONE_STAIRS
    val POLISHED_BLACKSTONE_SLAB: Block = Blocks.POLISHED_BLACKSTONE_SLAB
    val POLISHED_BLACKSTONE_PRESSURE_PLATE: Block = Blocks.POLISHED_BLACKSTONE_PRESSURE_PLATE
    val POLISHED_BLACKSTONE_BUTTON: Block = Blocks.POLISHED_BLACKSTONE_BUTTON
    val POLISHED_BLACKSTONE_WALL: Block = Blocks.POLISHED_BLACKSTONE_WALL
    val CHISELED_NETHER_BRICKS: Block = Blocks.CHISELED_NETHER_BRICKS
    val CRACKED_NETHER_BRICKS: Block = Blocks.CRACKED_NETHER_BRICKS
    val QUARTZ_BRICKS: Block = Blocks.QUARTZ_BRICKS
    val CANDLE: Block = Blocks.CANDLE
    val WHITE_CANDLE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("white_candle"))
    val ORANGE_CANDLE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("orange_candle"))
    val MAGENTA_CANDLE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("magenta_candle"))
    val LIGHT_BLUE_CANDLE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_blue_candle"))
    val YELLOW_CANDLE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("yellow_candle"))
    val LIME_CANDLE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("lime_candle"))
    val PINK_CANDLE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("pink_candle"))
    val GRAY_CANDLE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("gray_candle"))
    val LIGHT_GRAY_CANDLE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_gray_candle"))
    val CYAN_CANDLE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("cyan_candle"))
    val PURPLE_CANDLE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("purple_candle"))
    val BLUE_CANDLE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("blue_candle"))
    val BROWN_CANDLE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("brown_candle"))
    val GREEN_CANDLE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("green_candle"))
    val RED_CANDLE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("red_candle"))
    val BLACK_CANDLE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("black_candle"))
    val CANDLE_CAKE: Block = Blocks.CANDLE_CAKE
    val WHITE_CANDLE_CAKE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("white_candle_cake"))
    val ORANGE_CANDLE_CAKE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("orange_candle_cake"))
    val MAGENTA_CANDLE_CAKE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("magenta_candle_cake"))
    val LIGHT_BLUE_CANDLE_CAKE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_blue_candle_cake"))
    val YELLOW_CANDLE_CAKE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("yellow_candle_cake"))
    val LIME_CANDLE_CAKE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("lime_candle_cake"))
    val PINK_CANDLE_CAKE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("pink_candle_cake"))
    val GRAY_CANDLE_CAKE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("gray_candle_cake"))
    val LIGHT_GRAY_CANDLE_CAKE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("light_gray_candle_cake"))
    val CYAN_CANDLE_CAKE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("cyan_candle_cake"))
    val PURPLE_CANDLE_CAKE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("purple_candle_cake"))
    val BLUE_CANDLE_CAKE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("blue_candle_cake"))
    val BROWN_CANDLE_CAKE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("brown_candle_cake"))
    val GREEN_CANDLE_CAKE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("green_candle_cake"))
    val RED_CANDLE_CAKE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("red_candle_cake"))
    val BLACK_CANDLE_CAKE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("black_candle_cake"))
    val AMETHYST_BLOCK: Block = Blocks.AMETHYST_BLOCK
    val BUDDING_AMETHYST: Block = Blocks.BUDDING_AMETHYST
    val AMETHYST_CLUSTER: Block = Blocks.AMETHYST_CLUSTER
    val LARGE_AMETHYST_BUD: Block = Blocks.LARGE_AMETHYST_BUD
    val MEDIUM_AMETHYST_BUD: Block = Blocks.MEDIUM_AMETHYST_BUD
    val SMALL_AMETHYST_BUD: Block = Blocks.SMALL_AMETHYST_BUD
    val TUFF: Block = Blocks.TUFF
    val TUFF_SLAB: Block = Blocks.TUFF_SLAB
    val TUFF_STAIRS: Block = Blocks.TUFF_STAIRS
    val TUFF_WALL: Block = Blocks.TUFF_WALL
    val POLISHED_TUFF: Block = Blocks.POLISHED_TUFF
    val POLISHED_TUFF_SLAB: Block = Blocks.POLISHED_TUFF_SLAB
    val POLISHED_TUFF_STAIRS: Block = Blocks.POLISHED_TUFF_STAIRS
    val POLISHED_TUFF_WALL: Block = Blocks.POLISHED_TUFF_WALL
    val CHISELED_TUFF: Block = Blocks.CHISELED_TUFF
    val TUFF_BRICKS: Block = Blocks.TUFF_BRICKS
    val TUFF_BRICK_SLAB: Block = Blocks.TUFF_BRICK_SLAB
    val TUFF_BRICK_STAIRS: Block = Blocks.TUFF_BRICK_STAIRS
    val TUFF_BRICK_WALL: Block = Blocks.TUFF_BRICK_WALL
    val CHISELED_TUFF_BRICKS: Block = Blocks.CHISELED_TUFF_BRICKS
    val CALCITE: Block = Blocks.CALCITE
    val TINTED_GLASS: Block = Blocks.TINTED_GLASS
    val POWDER_SNOW: Block = Blocks.POWDER_SNOW
    val SCULK_SENSOR: Block = Blocks.SCULK_SENSOR
    val CALIBRATED_SCULK_SENSOR: Block = Blocks.CALIBRATED_SCULK_SENSOR
    val SCULK: Block = Blocks.SCULK
    val SCULK_VEIN: Block = Blocks.SCULK_VEIN
    val SCULK_CATALYST: Block = Blocks.SCULK_CATALYST
    val SCULK_SHRIEKER: Block = Blocks.SCULK_SHRIEKER
    val COPPER_BLOCK: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("copper_block"))
    val EXPOSED_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("exposed_copper"))
    val WEATHERED_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("weathered_copper"))
    val OXIDIZED_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("oxidized_copper"))
    val COPPER_ORE: Block = Blocks.COPPER_ORE
    val DEEPSLATE_COPPER_ORE: Block = Blocks.DEEPSLATE_COPPER_ORE
    val OXIDIZED_CUT_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("oxidized_cut_copper"))
    val WEATHERED_CUT_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("weathered_cut_copper"))
    val EXPOSED_CUT_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("exposed_cut_copper"))
    val CUT_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("cut_copper"))
    val OXIDIZED_CHISELED_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("oxidized_chiseled_copper"))
    val WEATHERED_CHISELED_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("weathered_chiseled_copper"))
    val EXPOSED_CHISELED_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("exposed_chiseled_copper"))
    val CHISELED_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("chiseled_copper"))
    val WAXED_OXIDIZED_CHISELED_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_oxidized_chiseled_copper"))
    val WAXED_WEATHERED_CHISELED_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_weathered_chiseled_copper"))
    val WAXED_EXPOSED_CHISELED_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_exposed_chiseled_copper"))
    val WAXED_CHISELED_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_chiseled_copper"))
    val OXIDIZED_CUT_COPPER_STAIRS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("oxidized_cut_copper_stairs"))
    val WEATHERED_CUT_COPPER_STAIRS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("weathered_cut_copper_stairs"))
    val EXPOSED_CUT_COPPER_STAIRS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("exposed_cut_copper_stairs"))
    val CUT_COPPER_STAIRS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("cut_copper_stairs"))
    val OXIDIZED_CUT_COPPER_SLAB: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("oxidized_cut_copper_slab"))
    val WEATHERED_CUT_COPPER_SLAB: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("weathered_cut_copper_slab"))
    val EXPOSED_CUT_COPPER_SLAB: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("exposed_cut_copper_slab"))
    val CUT_COPPER_SLAB: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("cut_copper_slab"))
    val WAXED_COPPER_BLOCK: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_copper_block"))
    val WAXED_WEATHERED_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_weathered_copper"))
    val WAXED_EXPOSED_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_exposed_copper"))
    val WAXED_OXIDIZED_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_oxidized_copper"))
    val WAXED_OXIDIZED_CUT_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_oxidized_cut_copper"))
    val WAXED_WEATHERED_CUT_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_weathered_cut_copper"))
    val WAXED_EXPOSED_CUT_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_exposed_cut_copper"))
    val WAXED_CUT_COPPER: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_cut_copper"))
    val WAXED_OXIDIZED_CUT_COPPER_STAIRS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_oxidized_cut_copper_stairs"))
    val WAXED_WEATHERED_CUT_COPPER_STAIRS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_weathered_cut_copper_stairs"))
    val WAXED_EXPOSED_CUT_COPPER_STAIRS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_exposed_cut_copper_stairs"))
    val WAXED_CUT_COPPER_STAIRS: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_cut_copper_stairs"))
    val WAXED_OXIDIZED_CUT_COPPER_SLAB: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_oxidized_cut_copper_slab"))
    val WAXED_WEATHERED_CUT_COPPER_SLAB: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_weathered_cut_copper_slab"))
    val WAXED_EXPOSED_CUT_COPPER_SLAB: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_exposed_cut_copper_slab"))
    val WAXED_CUT_COPPER_SLAB: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_cut_copper_slab"))
    val COPPER_DOOR: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("copper_door"))
    val EXPOSED_COPPER_DOOR: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("exposed_copper_door"))
    val OXIDIZED_COPPER_DOOR: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("oxidized_copper_door"))
    val WEATHERED_COPPER_DOOR: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("weathered_copper_door"))
    val WAXED_COPPER_DOOR: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_copper_door"))
    val WAXED_EXPOSED_COPPER_DOOR: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_exposed_copper_door"))
    val WAXED_OXIDIZED_COPPER_DOOR: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_oxidized_copper_door"))
    val WAXED_WEATHERED_COPPER_DOOR: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_weathered_copper_door"))
    val COPPER_TRAPDOOR: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("copper_trapdoor"))
    val EXPOSED_COPPER_TRAPDOOR: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("exposed_copper_trapdoor"))
    val OXIDIZED_COPPER_TRAPDOOR: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("oxidized_copper_trapdoor"))
    val WEATHERED_COPPER_TRAPDOOR: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("weathered_copper_trapdoor"))
    val WAXED_COPPER_TRAPDOOR: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_copper_trapdoor"))
    val WAXED_EXPOSED_COPPER_TRAPDOOR: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_exposed_copper_trapdoor"))
    val WAXED_OXIDIZED_COPPER_TRAPDOOR: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_oxidized_copper_trapdoor"))
    val WAXED_WEATHERED_COPPER_TRAPDOOR: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_weathered_copper_trapdoor"))
    val COPPER_GRATE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("copper_grate"))
    val EXPOSED_COPPER_GRATE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("exposed_copper_grate"))
    val WEATHERED_COPPER_GRATE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("weathered_copper_grate"))
    val OXIDIZED_COPPER_GRATE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("oxidized_copper_grate"))
    val WAXED_COPPER_GRATE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_copper_grate"))
    val WAXED_EXPOSED_COPPER_GRATE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_exposed_copper_grate"))
    val WAXED_WEATHERED_COPPER_GRATE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_weathered_copper_grate"))
    val WAXED_OXIDIZED_COPPER_GRATE: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_oxidized_copper_grate"))
    val COPPER_BULB: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("copper_bulb"))
    val EXPOSED_COPPER_BULB: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("exposed_copper_bulb"))
    val WEATHERED_COPPER_BULB: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("weathered_copper_bulb"))
    val OXIDIZED_COPPER_BULB: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("oxidized_copper_bulb"))
    val WAXED_COPPER_BULB: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_copper_bulb"))
    val WAXED_EXPOSED_COPPER_BULB: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_exposed_copper_bulb"))
    val WAXED_WEATHERED_COPPER_BULB: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_weathered_copper_bulb"))
    val WAXED_OXIDIZED_COPPER_BULB: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("waxed_oxidized_copper_bulb"))
    val LIGHTNING_ROD: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("lightning_rod"))
    val POINTED_DRIPSTONE: Block = Blocks.POINTED_DRIPSTONE
    val DRIPSTONE_BLOCK: Block = Blocks.DRIPSTONE_BLOCK
    val CAVE_VINES: Block = Blocks.CAVE_VINES
    val CAVE_VINES_PLANT: Block = Blocks.CAVE_VINES_PLANT
    val SPORE_BLOSSOM: Block = Blocks.SPORE_BLOSSOM
    val AZALEA: Block = Blocks.AZALEA
    val FLOWERING_AZALEA: Block = Blocks.FLOWERING_AZALEA
    val MOSS_CARPET: Block = Blocks.MOSS_CARPET
    val PINK_PETALS: Block = Blocks.PINK_PETALS
    val WILDFLOWERS: Block = Blocks.WILDFLOWERS
    val LEAF_LITTER: Block = Blocks.LEAF_LITTER
    val MOSS_BLOCK: Block = Blocks.MOSS_BLOCK
    val BIG_DRIPLEAF: Block = Blocks.BIG_DRIPLEAF
    val BIG_DRIPLEAF_STEM: Block = Blocks.BIG_DRIPLEAF_STEM
    val SMALL_DRIPLEAF: Block = Blocks.SMALL_DRIPLEAF
    val HANGING_ROOTS: Block = Blocks.HANGING_ROOTS
    val ROOTED_DIRT: Block = Blocks.ROOTED_DIRT
    val MUD: Block = Blocks.MUD
    val DEEPSLATE: Block = Blocks.DEEPSLATE
    val COBBLED_DEEPSLATE: Block = Blocks.COBBLED_DEEPSLATE
    val COBBLED_DEEPSLATE_STAIRS: Block = Blocks.COBBLED_DEEPSLATE_STAIRS
    val COBBLED_DEEPSLATE_SLAB: Block = Blocks.COBBLED_DEEPSLATE_SLAB
    val COBBLED_DEEPSLATE_WALL: Block = Blocks.COBBLED_DEEPSLATE_WALL
    val POLISHED_DEEPSLATE: Block = Blocks.POLISHED_DEEPSLATE
    val POLISHED_DEEPSLATE_STAIRS: Block = Blocks.POLISHED_DEEPSLATE_STAIRS
    val POLISHED_DEEPSLATE_SLAB: Block = Blocks.POLISHED_DEEPSLATE_SLAB
    val POLISHED_DEEPSLATE_WALL: Block = Blocks.POLISHED_DEEPSLATE_WALL
    val DEEPSLATE_TILES: Block = Blocks.DEEPSLATE_TILES
    val DEEPSLATE_TILE_STAIRS: Block = Blocks.DEEPSLATE_TILE_STAIRS
    val DEEPSLATE_TILE_SLAB: Block = Blocks.DEEPSLATE_TILE_SLAB
    val DEEPSLATE_TILE_WALL: Block = Blocks.DEEPSLATE_TILE_WALL
    val DEEPSLATE_BRICKS: Block = Blocks.DEEPSLATE_BRICKS
    val DEEPSLATE_BRICK_STAIRS: Block = Blocks.DEEPSLATE_BRICK_STAIRS
    val DEEPSLATE_BRICK_SLAB: Block = Blocks.DEEPSLATE_BRICK_SLAB
    val DEEPSLATE_BRICK_WALL: Block = Blocks.DEEPSLATE_BRICK_WALL
    val CHISELED_DEEPSLATE: Block = Blocks.CHISELED_DEEPSLATE
    val CRACKED_DEEPSLATE_BRICKS: Block = Blocks.CRACKED_DEEPSLATE_BRICKS
    val CRACKED_DEEPSLATE_TILES: Block = Blocks.CRACKED_DEEPSLATE_TILES
    val INFESTED_DEEPSLATE: Block = Blocks.INFESTED_DEEPSLATE
    val SMOOTH_BASALT: Block = Blocks.SMOOTH_BASALT
    val RAW_IRON_BLOCK: Block = Blocks.RAW_IRON_BLOCK
    val RAW_COPPER_BLOCK: Block = Blocks.RAW_COPPER_BLOCK
    val RAW_GOLD_BLOCK: Block = Blocks.RAW_GOLD_BLOCK
    val POTTED_AZALEA_BUSH: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("potted_azalea_bush"))
    val POTTED_FLOWERING_AZALEA_BUSH: Block get() = BuiltInRegistries.BLOCK.getValue(Identifier.withDefaultNamespace("potted_flowering_azalea_bush"))
    val OCHRE_FROGLIGHT: Block = Blocks.OCHRE_FROGLIGHT
    val VERDANT_FROGLIGHT: Block = Blocks.VERDANT_FROGLIGHT
    val PEARLESCENT_FROGLIGHT: Block = Blocks.PEARLESCENT_FROGLIGHT
    val FROGSPAWN: Block = Blocks.FROGSPAWN
    val REINFORCED_DEEPSLATE: Block = Blocks.REINFORCED_DEEPSLATE
    val DECORATED_POT: Block = Blocks.DECORATED_POT
    val CRAFTER: Block = Blocks.CRAFTER
    val TRIAL_SPAWNER: Block = Blocks.TRIAL_SPAWNER
    val VAULT: Block = Blocks.VAULT
    val HEAVY_CORE: Block = Blocks.HEAVY_CORE
    val PALE_MOSS_BLOCK: Block = Blocks.PALE_MOSS_BLOCK
    val PALE_MOSS_CARPET: Block = Blocks.PALE_MOSS_CARPET
    val PALE_HANGING_MOSS: Block = Blocks.PALE_HANGING_MOSS
    val OPEN_EYEBLOSSOM: Block = Blocks.OPEN_EYEBLOSSOM
    val CLOSED_EYEBLOSSOM: Block = Blocks.CLOSED_EYEBLOSSOM
    val POTTED_OPEN_EYEBLOSSOM: Block = Blocks.POTTED_OPEN_EYEBLOSSOM
    val POTTED_CLOSED_EYEBLOSSOM: Block = Blocks.POTTED_CLOSED_EYEBLOSSOM
    val FIREFLY_BUSH: Block = Blocks.FIREFLY_BUSH
}
