modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/cao-awa/conium/issues"
license = "GPLv3"

[[mods]]
modId = "conium"
version = "${version}"
displayName = "Conium"
authors = "cao_awa"
description = '''
Conium is a datapack and script framework for modern Minecraft, it provides very diverse features without Java coding, Conium lets you complete your mods only using datapacks.
'''
#logoFile = ""

[[dependencies.conium]]
modId = "neoforge"
type = "required"
versionRange = "[21.6.8-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.conium]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.6]"
ordering = "NONE"
side = "BOTH"

#[[dependencies.conium]]
#modId = "architectury"
#type = "required"
#versionRange = "[15.0.1,)"
#ordering = "AFTER"
#side = "BOTH"

[[mixins]]
config = "conium.mixins.json"

[[accessTransformers]]
## The file is relative to the output directory of the resources, or the root path inside the jar when compiled
## The 'resources' directory represents the root output directory of the resources
file = "conium_transformer.cfg"